include_guard(GLOBAL)

# Resolve platform, architecture, and config into canonical lowercase names.
function(platform_resolve_target platform arch config out_platform out_arch out_config)
	string(TOLOWER "${platform}" _platform)
	string(TOLOWER "${arch}" _arch)
	string(TOLOWER "${config}" _cfg)

	if(NOT _cfg MATCHES "^(debug|release)$")
		message(FATAL_ERROR "[Platform] Config must be Debug or Release: ${config}")
	endif()

	# Collapse common architecture aliases into one canonical token.
	if(_arch MATCHES "^(amd64|x86_64|x64)$")
		set(_arch "x64")
	elseif(_arch MATCHES "^(aarch64|arm64|arm64-v8a)$")
		set(_arch "arm64")
	elseif(_arch MATCHES "^(arm|armeabi-v7a)$")
		set(_arch "arm")
	elseif(_arch MATCHES "^(i[3-6]86|x86)$")
		set(_arch "x86")
	elseif(_arch MATCHES "^(wasm|wasm32)$")
		set(_arch "wasm32")
	endif()

	# Validate the token per platform and map it to the platform naming convention.
	if(_platform STREQUAL "windows")
		if(NOT _arch MATCHES "^(x64|arm64|x86)$")
			message(FATAL_ERROR "[Platform] Unsupported Windows architecture: ${arch}")
		endif()
	elseif(_platform STREQUAL "android")
		if(_arch STREQUAL "arm64")
			set(_arch "arm64-v8a")
		elseif(_arch STREQUAL "arm")
			set(_arch "armeabi-v7a")
		elseif(_arch STREQUAL "x64")
			set(_arch "x86_64")
		elseif(NOT _arch STREQUAL "x86")
			message(FATAL_ERROR "[Platform] Unsupported Android architecture: ${arch}")
		endif()
	elseif(_platform STREQUAL "web")
		if(NOT _arch STREQUAL "wasm32")
			message(FATAL_ERROR "[Platform] Unsupported Web architecture: ${arch}")
		endif()
	else()
		message(FATAL_ERROR "[Platform] Unsupported platform: ${platform}")
	endif()

	set(${out_platform} "${_platform}" PARENT_SCOPE)
	set(${out_arch} "${_arch}" PARENT_SCOPE)
	set(${out_config} "${_cfg}" PARENT_SCOPE)
endfunction()
