// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_WORD_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_WORD_CONFIG_GEN_H_

#include "render/config/line/normal/main/syllable/word/animation/index.gen.h"

namespace music_lyric_player::render::config::line::normal::main::syllable::word {
	/**
	 * Rendering settings of each timed word.
	 */
	struct Root {
		/**
		 * Float and reveal animations of the word.
		 */
		::music_lyric_player::render::config::line::normal::main::syllable::word::animation::Root animation;
	};

	struct RootPatch {
		::music_lyric_player::render::config::line::normal::main::syllable::word::animation::RootPatch animation;
	};

	struct RootChange {
		::music_lyric_player::render::config::line::normal::main::syllable::word::animation::RootChange animation;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.animation, patch.animation);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.animation = diff(prev.animation, next.animation);
		change.any = change.animation.any;
		return change;
	}

} // namespace music_lyric_player::render::config::line::normal::main::syllable::word

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_WORD_CONFIG_GEN_H_
