// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_WORD_ANIMATION_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_WORD_ANIMATION_CONFIG_GEN_H_

#include <optional>

namespace music_lyric_player::render::config::line::normal::main::syllable::word::animation {
	/**
	 * Vertical motion applied to each timed word.
	 */
	struct FloatConfig {
		/**
		 * Whether timed words float while they are sung.
		 *
		 * @default true
		 */
		bool enabled = true;
		/**
		 * Starting vertical offset in logical pixels.
		 *
		 * @default 0.0
		 */
		double from = 0.0;
		/**
		 * Ending vertical offset in logical pixels.
		 *
		 * @default -2.0
		 */
		double to = -2.0;
	};

	/**
	 * Soft-edge sizing of the karaoke reveal mask.
	 */
	struct MaskFeatherConfig {
		/**
		 * Base feather width as a multiple of word height.
		 *
		 * @default 0.5
		 * @minimum 0
		 * @maximum 2
		 */
		double normal = 0.5;
		/**
		 * Feather multiplier for the first word.
		 *
		 * @default 1.5
		 * @minimum 0
		 * @maximum 5
		 */
		double first = 1.5;
		/**
		 * Feather multiplier for the last word.
		 *
		 * @default 0.5
		 * @minimum 0
		 * @maximum 5
		 */
		double last = 0.5;
	};

	/**
	 * Left-to-right karaoke reveal mask.
	 */
	struct MaskConfig {
		/**
		 * Whether active words reveal progressively instead of switching immediately.
		 *
		 * @default true
		 */
		bool enabled = true;
		/**
		 * Soft-edge sizing of the reveal boundary.
		 */
		MaskFeatherConfig feather;
	};

	/**
	 * Animation settings of timed words.
	 */
	struct Root {
		/**
		 * Vertical word motion.
		 */
		FloatConfig floating;
		/**
		 * Karaoke color reveal mask.
		 */
		MaskConfig mask;
	};

	struct FloatConfigPatch {
		::std::optional<bool> enabled;
		::std::optional<double> from;
		::std::optional<double> to;
	};

	struct MaskFeatherConfigPatch {
		::std::optional<double> normal;
		::std::optional<double> first;
		::std::optional<double> last;
	};

	struct MaskConfigPatch {
		::std::optional<bool> enabled;
		MaskFeatherConfigPatch feather;
	};

	struct RootPatch {
		FloatConfigPatch floating;
		MaskConfigPatch mask;
	};

	struct FloatConfigChange {
		bool enabled = false;
		bool from = false;
		bool to = false;
		bool any = false;
	};

	struct MaskFeatherConfigChange {
		bool normal = false;
		bool first = false;
		bool last = false;
		bool any = false;
	};

	struct MaskConfigChange {
		bool enabled = false;
		MaskFeatherConfigChange feather;
		bool any = false;
	};

	struct RootChange {
		FloatConfigChange floating;
		MaskConfigChange mask;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(FloatConfig& cfg, const FloatConfigPatch& patch) {
		if (patch.enabled.has_value()) {
			cfg.enabled = *patch.enabled;
		}
		if (patch.from.has_value()) {
			cfg.from = *patch.from;
		}
		if (patch.to.has_value()) {
			cfg.to = *patch.to;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(MaskFeatherConfig& cfg, const MaskFeatherConfigPatch& patch) {
		if (patch.normal.has_value()) {
			cfg.normal = *patch.normal;
		}
		if (patch.first.has_value()) {
			cfg.first = *patch.first;
		}
		if (patch.last.has_value()) {
			cfg.last = *patch.last;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(MaskConfig& cfg, const MaskConfigPatch& patch) {
		if (patch.enabled.has_value()) {
			cfg.enabled = *patch.enabled;
		}
		apply(cfg.feather, patch.feather);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.floating, patch.floating);
		apply(cfg.mask, patch.mask);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline FloatConfigChange diff(const FloatConfig& prev, const FloatConfig& next) {
		FloatConfigChange change;
		change.enabled = prev.enabled != next.enabled;
		change.from = prev.from != next.from;
		change.to = prev.to != next.to;
		change.any = change.enabled || change.from || change.to;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline MaskFeatherConfigChange diff(const MaskFeatherConfig& prev, const MaskFeatherConfig& next) {
		MaskFeatherConfigChange change;
		change.normal = prev.normal != next.normal;
		change.first = prev.first != next.first;
		change.last = prev.last != next.last;
		change.any = change.normal || change.first || change.last;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline MaskConfigChange diff(const MaskConfig& prev, const MaskConfig& next) {
		MaskConfigChange change;
		change.enabled = prev.enabled != next.enabled;
		change.feather = diff(prev.feather, next.feather);
		change.any = change.enabled || change.feather.any;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.floating = diff(prev.floating, next.floating);
		change.mask = diff(prev.mask, next.mask);
		change.any = change.floating.any || change.mask.any;
		return change;
	}

} // namespace music_lyric_player::render::config::line::normal::main::syllable::word::animation

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_WORD_ANIMATION_CONFIG_GEN_H_
