// clang-format off

// Generated by generate-config script. DO NOT EDIT.
// To change config, edit the schema and regenerate with generate-config script.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_CONFIG_GEN_H_

#include "rendering/config/line/normal/main/syllable.gen.h"

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::line::normal::main {
	/**
	 * Main normal-line rendering mode.
	 */
	enum class Use {
		Plain,
		Syllable,
	};

	/**
	 * Rendering mode and settings of a normal line's main content.
	 */
	struct Root {
		/**
		 * Preferred renderer; lyrics without word timing still fall back to plain text.
		 *
		 * @default Use::Syllable
		 */
		::music_lyric_player::utils::config::Property<Use> use = Use::Syllable;
		/**
		 * Word-timed karaoke rendering settings.
		 */
		::music_lyric_player::rendering::config::line::normal::main::syllable::Root syllable;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			if (src.use.assigned()) dst.use = src.use.value();
			overlay(dst.syllable, src.syllable, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.use == next.use)) delta.use = next.use.value();
			capture(delta.syllable, prev.syllable, next.syllable, key);
		}
	};

} // namespace music_lyric_player::rendering::config::line::normal::main

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_CONFIG_GEN_H_
