// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_CONFIG_GEN_H_

#include <optional>

#include "rendering/config/line/normal/main/syllable.gen.h"

namespace music_lyric_player::rendering::config::line::normal::main {
	/**
	 * Main normal-line rendering mode.
	 */
	enum class Use {
		Plain,
		Syllable,
	};

	/**
	 * Rendering mode and settings of a normal line's main content.
	 */
	struct Root {
		/**
		 * Preferred renderer; lyrics without word timing still fall back to plain text.
		 *
		 * @default Use::Syllable
		 */
		Use use = Use::Syllable;
		/**
		 * Word-timed karaoke rendering settings.
		 */
		::music_lyric_player::rendering::config::line::normal::main::syllable::Root syllable;
	};

	struct RootPatch {
		::std::optional<Use> use;
		::music_lyric_player::rendering::config::line::normal::main::syllable::RootPatch syllable;
	};

	struct RootChange {
		bool use = false;
		::music_lyric_player::rendering::config::line::normal::main::syllable::RootChange syllable;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.use.has_value()) {
			cfg.use = *patch.use;
		}
		apply(cfg.syllable, patch.syllable);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.use = prev.use != next.use;
		change.syllable = diff(prev.syllable, next.syllable);
		change.any = change.use || change.syllable.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::line::normal::main

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_CONFIG_GEN_H_
