// clang-format off

// Generated by script/generate-config.py from syllable.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_CONFIG_GEN_H_

#include "rendering/config/common/index.gen.h"

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::line::normal::main::syllable {
	/**
	 * Vertical motion applied to each timed word.
	 */
	struct FloatConfig {
		/**
		 * Whether timed words float while they are sung.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> enabled = true;
		/**
		 * Starting vertical offset in logical pixels.
		 *
		 * @default 0.0
		 */
		::music_lyric_player::utils::config::Property<double> from = 0.0;
		/**
		 * Ending vertical offset in logical pixels.
		 *
		 * @default -2.0
		 */
		::music_lyric_player::utils::config::Property<double> to = -2.0;

		bool operator==(const FloatConfig&) const = default;

		friend void overlay(FloatConfig& dst, const FloatConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.enabled.assigned()) dst.enabled = src.enabled.value();
			if (src.from.assigned()) dst.from = src.from.value();
			if (src.to.assigned()) dst.to = src.to.value();
		}

		friend void capture(FloatConfig& delta, const FloatConfig& prev, const FloatConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.enabled == next.enabled)) delta.enabled = next.enabled.value();
			if (!(prev.from == next.from)) delta.from = next.from.value();
			if (!(prev.to == next.to)) delta.to = next.to.value();
		}
	};

	/**
	 * Soft-edge sizing of the karaoke reveal mask.
	 */
	struct MaskFeatherConfig {
		/**
		 * Base feather width as a multiple of word height.
		 *
		 * @default 0.5
		 * @minimum 0
		 * @maximum 2
		 */
		::music_lyric_player::utils::config::Property<double> normal = 0.5;
		/**
		 * Feather multiplier for the first word.
		 *
		 * @default 1.5
		 * @minimum 0
		 * @maximum 5
		 */
		::music_lyric_player::utils::config::Property<double> first = 1.5;
		/**
		 * Feather multiplier for the last word.
		 *
		 * @default 0.5
		 * @minimum 0
		 * @maximum 5
		 */
		::music_lyric_player::utils::config::Property<double> last = 0.5;

		bool operator==(const MaskFeatherConfig&) const = default;

		friend void overlay(MaskFeatherConfig& dst, const MaskFeatherConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.normal.assigned()) dst.normal = src.normal.value();
			if (src.first.assigned()) dst.first = src.first.value();
			if (src.last.assigned()) dst.last = src.last.value();
		}

		friend void capture(MaskFeatherConfig& delta, const MaskFeatherConfig& prev, const MaskFeatherConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.normal == next.normal)) delta.normal = next.normal.value();
			if (!(prev.first == next.first)) delta.first = next.first.value();
			if (!(prev.last == next.last)) delta.last = next.last.value();
		}
	};

	/**
	 * Left-to-right karaoke reveal mask.
	 */
	struct MaskConfig {
		/**
		 * Whether active words reveal progressively instead of switching immediately.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> enabled = true;
		/**
		 * Soft-edge sizing of the reveal boundary.
		 */
		MaskFeatherConfig feather;

		bool operator==(const MaskConfig&) const = default;

		friend void overlay(MaskConfig& dst, const MaskConfig& src, ::music_lyric_player::utils::config::Access key) {
			if (src.enabled.assigned()) dst.enabled = src.enabled.value();
			overlay(dst.feather, src.feather, key);
		}

		friend void capture(MaskConfig& delta, const MaskConfig& prev, const MaskConfig& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.enabled == next.enabled)) delta.enabled = next.enabled.value();
			capture(delta.feather, prev.feather, next.feather, key);
		}
	};

	/**
	 * Animation settings of timed words.
	 */
	struct WordAnimationConfig {
		/**
		 * Vertical word motion.
		 */
		FloatConfig floating;
		/**
		 * Karaoke color reveal mask.
		 */
		MaskConfig mask;

		bool operator==(const WordAnimationConfig&) const = default;

		friend void overlay(WordAnimationConfig& dst, const WordAnimationConfig& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.floating, src.floating, key);
			overlay(dst.mask, src.mask, key);
		}

		friend void capture(WordAnimationConfig& delta, const WordAnimationConfig& prev, const WordAnimationConfig& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.floating, prev.floating, next.floating, key);
			capture(delta.mask, prev.mask, next.mask, key);
		}
	};

	/**
	 * Rendering settings of each timed word.
	 */
	struct WordConfig {
		/**
		 * Float and reveal animations of the word.
		 */
		WordAnimationConfig animation;

		bool operator==(const WordConfig&) const = default;

		friend void overlay(WordConfig& dst, const WordConfig& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.animation, src.animation, key);
		}

		friend void capture(WordConfig& delta, const WordConfig& prev, const WordConfig& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.animation, prev.animation, next.animation, key);
		}
	};

	/**
	 * Word-timed karaoke rendering settings.
	 */
	struct Root {
		/**
		 * Font of the karaoke main content; inherits the base line font when unset.
		 */
		::music_lyric_player::rendering::config::common::FontConfig font;
		/**
		 * Inactive, active, and played styles of the karaoke main content; inherit the base line styles when unset.
		 */
		::music_lyric_player::rendering::config::common::StateStyleConfig style;
		/**
		 * Timed word rendering and animation settings.
		 */
		WordConfig word;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.font, src.font, key);
			overlay(dst.style, src.style, key);
			overlay(dst.word, src.word, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.font, prev.font, next.font, key);
			capture(delta.style, prev.style, next.style, key);
			capture(delta.word, prev.word, next.word, key);
		}
	};

} // namespace music_lyric_player::rendering::config::line::normal::main::syllable

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_CONFIG_GEN_H_
