// clang-format off

// Generated by script/generate-config.py from config.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_CONFIG_GEN_H_

#include <optional>

namespace music_lyric_player::playback::config {
	/**
	 * The global layer of the three-layer offset (global + meta + temp).
	 */
	struct OffsetConfig {
		double global = 0.0;  // ms applied to every song
		bool useMeta = true;  // apply the lyric's own meta offset
		bool resetTempOnLyricChange = true;  // clear the temp offset when a new lyric loads
	};

	/**
	 * Timing-engine configuration.
	 */
	struct Root {
		bool bridgeActive = true;  // fill active-index gaps
		double mergeWindow = 300.0;  // ms cluster for joint deactivation
		int mergeLimit = 3;  // max lines per merge batch
		OffsetConfig offset;  // the three-layer offset's global settings
	};

	struct OffsetConfigPatch {
		::std::optional<double> global;
		::std::optional<bool> useMeta;
		::std::optional<bool> resetTempOnLyricChange;
	};

	struct RootPatch {
		::std::optional<bool> bridgeActive;
		::std::optional<double> mergeWindow;
		::std::optional<int> mergeLimit;
		OffsetConfigPatch offset;
	};

	struct OffsetConfigChange {
		bool global = false;
		bool useMeta = false;
		bool resetTempOnLyricChange = false;
		bool any = false;
	};

	struct RootChange {
		bool bridgeActive = false;
		bool mergeWindow = false;
		bool mergeLimit = false;
		OffsetConfigChange offset;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(OffsetConfig& cfg, const OffsetConfigPatch& patch) {
		if (patch.global.has_value()) {
			cfg.global = *patch.global;
		}
		if (patch.useMeta.has_value()) {
			cfg.useMeta = *patch.useMeta;
		}
		if (patch.resetTempOnLyricChange.has_value()) {
			cfg.resetTempOnLyricChange = *patch.resetTempOnLyricChange;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.bridgeActive.has_value()) {
			cfg.bridgeActive = *patch.bridgeActive;
		}
		if (patch.mergeWindow.has_value()) {
			cfg.mergeWindow = *patch.mergeWindow;
		}
		if (patch.mergeLimit.has_value()) {
			cfg.mergeLimit = *patch.mergeLimit;
		}
		apply(cfg.offset, patch.offset);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline OffsetConfigChange diff(const OffsetConfig& prev, const OffsetConfig& next) {
		OffsetConfigChange change;
		change.global = prev.global != next.global;
		change.useMeta = prev.useMeta != next.useMeta;
		change.resetTempOnLyricChange = prev.resetTempOnLyricChange != next.resetTempOnLyricChange;
		change.any = change.global || change.useMeta || change.resetTempOnLyricChange;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.bridgeActive = prev.bridgeActive != next.bridgeActive;
		change.mergeWindow = prev.mergeWindow != next.mergeWindow;
		change.mergeLimit = prev.mergeLimit != next.mergeLimit;
		change.offset = diff(prev.offset, next.offset);
		change.any = change.bridgeActive || change.mergeWindow || change.mergeLimit || change.offset.any;
		return change;
	}

	/**
	 * Built-in defaults (every field at its schema default); the fallback when a config value fails to parse.
	 */
	inline const Root Default{};

} // namespace music_lyric_player::playback::config

#endif // MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_CONFIG_GEN_H_
