// clang-format off
// Generated by script/generate-config.py from config.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"

namespace music_lyric_player::playback {
	/**
	 * The global layer of the three-layer offset (global + meta + temp).
	 */
	struct OffsetConfig {
		double global = 0.0;  // ms applied to every song
		bool useMeta = true;  // apply the lyric's own meta offset
		bool resetTempOnLyricChange = true;  // clear the temp offset when a new lyric loads
	};

	/**
	 * Timing-engine configuration.
	 */
	struct Config {
		bool bridgeActive = true;  // fill active-index gaps
		double mergeWindow = 300.0;  // ms cluster for joint deactivation
		int mergeLimit = 3;  // max lines per merge batch
		OffsetConfig offset;  // the three-layer offset's global settings
	};

	struct OffsetConfigPatch {
		::std::optional<double> global;
		::std::optional<bool> useMeta;
		::std::optional<bool> resetTempOnLyricChange;
	};

	struct ConfigPatch {
		::std::optional<bool> bridgeActive;
		::std::optional<double> mergeWindow;
		::std::optional<int> mergeLimit;
		OffsetConfigPatch offset;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(OffsetConfig& cfg, const OffsetConfigPatch& patch) {
		if (patch.global.has_value()) {
			cfg.global = *patch.global;
		}
		if (patch.useMeta.has_value()) {
			cfg.useMeta = *patch.useMeta;
		}
		if (patch.resetTempOnLyricChange.has_value()) {
			cfg.resetTempOnLyricChange = *patch.resetTempOnLyricChange;
		}
	}

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Config& cfg, const ConfigPatch& patch) {
		if (patch.bridgeActive.has_value()) {
			cfg.bridgeActive = *patch.bridgeActive;
		}
		if (patch.mergeWindow.has_value()) {
			cfg.mergeWindow = *patch.mergeWindow;
		}
		if (patch.mergeLimit.has_value()) {
			cfg.mergeLimit = *patch.mergeLimit;
		}
		applyConfigPatch(cfg.offset, patch.offset);
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const OffsetConfig& prev, const OffsetConfig& next, const ::std::string& prefix, ::music_lyric_player::ChangeKeys& keys) {
		if (prev.global != next.global) {
			keys.insert(prefix + "global");
		}
		if (prev.useMeta != next.useMeta) {
			keys.insert(prefix + "useMeta");
		}
		if (prev.resetTempOnLyricChange != next.resetTempOnLyricChange) {
			keys.insert(prefix + "resetTempOnLyricChange");
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Config& prev, const Config& next, const ::std::string& prefix, ::music_lyric_player::ChangeKeys& keys) {
		if (prev.bridgeActive != next.bridgeActive) {
			keys.insert(prefix + "bridgeActive");
		}
		if (prev.mergeWindow != next.mergeWindow) {
			keys.insert(prefix + "mergeWindow");
		}
		if (prev.mergeLimit != next.mergeLimit) {
			keys.insert(prefix + "mergeLimit");
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.offset, next.offset, prefix + "offset" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "offset");
			}
		}
	}

	namespace OffsetConfigKeys {
		inline constexpr ::std::string_view global{"global"};
		inline constexpr ::std::string_view useMeta{"useMeta"};
		inline constexpr ::std::string_view resetTempOnLyricChange{"resetTempOnLyricChange"};
	} // namespace OffsetConfigKeys

	namespace ConfigKeys {
		inline constexpr ::std::string_view bridgeActive{"bridgeActive"};
		inline constexpr ::std::string_view mergeWindow{"mergeWindow"};
		inline constexpr ::std::string_view mergeLimit{"mergeLimit"};
		namespace offset {
			inline constexpr ::std::string_view global{"offset.global"};
			inline constexpr ::std::string_view useMeta{"offset.useMeta"};
			inline constexpr ::std::string_view resetTempOnLyricChange{"offset.resetTempOnLyricChange"};
		} // namespace offset
	} // namespace ConfigKeys

} // namespace music_lyric_player::playback

#endif // MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_GEN_H_
// clang-format on
