// clang-format off

// Generated by script/generate-config.py from config.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_CONFIG_GEN_H_

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::playback::config {
	/**
	 * The global layer of the three-layer offset (global + meta + temp).
	 */
	struct OffsetConfig {
		::music_lyric_player::utils::config::Property<double> global = 0.0;  // ms applied to every song
		::music_lyric_player::utils::config::Property<bool> useMeta = true;  // apply the lyric's own meta offset
		::music_lyric_player::utils::config::Property<bool> resetTempOnLyricChange = true;  // clear the temp offset when a new lyric loads

		bool operator==(const OffsetConfig&) const = default;

		friend void overlay(OffsetConfig& dst, const OffsetConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.global.assigned()) dst.global = src.global.value();
			if (src.useMeta.assigned()) dst.useMeta = src.useMeta.value();
			if (src.resetTempOnLyricChange.assigned()) dst.resetTempOnLyricChange = src.resetTempOnLyricChange.value();
		}

		friend void capture(OffsetConfig& delta, const OffsetConfig& prev, const OffsetConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.global == next.global)) delta.global = next.global.value();
			if (!(prev.useMeta == next.useMeta)) delta.useMeta = next.useMeta.value();
			if (!(prev.resetTempOnLyricChange == next.resetTempOnLyricChange)) delta.resetTempOnLyricChange = next.resetTempOnLyricChange.value();
		}
	};

	/**
	 * Timing-engine configuration.
	 */
	struct Root {
		::music_lyric_player::utils::config::Property<bool> bridgeActive = true;  // fill active-index gaps
		::music_lyric_player::utils::config::Property<double> mergeWindow = 300.0;  // ms cluster for joint deactivation
		::music_lyric_player::utils::config::Property<int> mergeLimit = 3;  // max lines per merge batch
		OffsetConfig offset;  // the three-layer offset's global settings

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			if (src.bridgeActive.assigned()) dst.bridgeActive = src.bridgeActive.value();
			if (src.mergeWindow.assigned()) dst.mergeWindow = src.mergeWindow.value();
			if (src.mergeLimit.assigned()) dst.mergeLimit = src.mergeLimit.value();
			overlay(dst.offset, src.offset, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.bridgeActive == next.bridgeActive)) delta.bridgeActive = next.bridgeActive.value();
			if (!(prev.mergeWindow == next.mergeWindow)) delta.mergeWindow = next.mergeWindow.value();
			if (!(prev.mergeLimit == next.mergeLimit)) delta.mergeLimit = next.mergeLimit.value();
			capture(delta.offset, prev.offset, next.offset, key);
		}

		/**
		 * Resolves the accumulated overrides into a fully-concrete config: resets `out` to the defaults, overlays the overrides, then fills every leaf that was not explicitly set from its inherited source.
		 */
		friend void resolve(Root& out, const Root& overrides, ::music_lyric_player::utils::config::Access key) {
			out = Root{};
			overlay(out, overrides, key);
		}
	};

	/**
	 * Built-in defaults (every field at its schema default); the fallback when a config value fails to parse.
	 */
	inline const Root Default{};

} // namespace music_lyric_player::playback::config

#endif // MUSIC_LYRIC_PLAYER_PLAYBACK_CONFIG_CONFIG_GEN_H_
