// clang-format off
// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_COMMON_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_COMMON_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"

namespace music_lyric_player::render::config::common {
	/**
	 * Font appearance shared by lyric lines and their annotation sub-lines.
	 */
	struct FontConfig {
		/**
		 * Font family name; empty uses the platform default.
		 *
		 * @example "PingFang SC"
		 */
		::std::string family = {};
		/**
		 * Font size; a bare number or `px` is absolute.
		 * `%` is relative to the parent line's font size (e.g. translation / background lines).
		 *
		 * @default "34px"
		 * @example 34
		 * @example "34px"
		 * @example "80%"
		 */
		::std::string size = "34px";
	};

	/**
	 * Visual style for a single render state.
	 */
	struct StyleConfig {
		/**
		 * Color of the render state.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#000000"
		 * @example "#fff"
		 * @example "rgba(255, 255, 255, 0.8)"
		 */
		::std::string color = "#000000";
	};

	struct FontConfigPatch {
		::std::optional<::std::string> family;
		::std::optional<::std::string> size;
	};

	struct StyleConfigPatch {
		::std::optional<::std::string> color;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(FontConfig& cfg, const FontConfigPatch& patch) {
		if (patch.family.has_value()) {
			cfg.family = *patch.family;
		}
		if (patch.size.has_value()) {
			cfg.size = *patch.size;
		}
	}

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(StyleConfig& cfg, const StyleConfigPatch& patch) {
		if (patch.color.has_value()) {
			cfg.color = *patch.color;
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const FontConfig& prev, const FontConfig& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.family != next.family) {
			keys.insert(prefix + "family");
		}
		if (prev.size != next.size) {
			keys.insert(prefix + "size");
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const StyleConfig& prev, const StyleConfig& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.color != next.color) {
			keys.insert(prefix + "color");
		}
	}

	namespace FontConfigKeys {
		inline constexpr ::std::string_view family{"family"};
		inline constexpr ::std::string_view size{"size"};
	} // namespace FontConfigKeys

	namespace StyleConfigKeys {
		inline constexpr ::std::string_view color{"color"};
	} // namespace StyleConfigKeys

} // namespace music_lyric_player::render::config::common

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_COMMON_CONFIG_GEN_H_
// clang-format on
