// Generated by script/generate-config/main.py from config.schema.json. DO NOT EDIT.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONFIG_GLAZE_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONFIG_GLAZE_H_

#include "glaze/json.hpp"
#include "rendering/config/config.gen.h"

template <>
struct glz::meta<::music_lyric_player::rendering::config::layout::Align> {
	using enum ::music_lyric_player::rendering::config::layout::Align;
	static constexpr auto value = enumerate(Left, Center, Right);
};

template <>
struct glz::meta<::music_lyric_player::rendering::config::scroll::Mode> {
	using enum ::music_lyric_player::rendering::config::scroll::Mode;
	static constexpr auto value = enumerate(Smooth, Ripple, Directional, Stagger);
};

template <>
struct glz::meta<::music_lyric_player::rendering::config::line::normal::main::Use> {
	using enum ::music_lyric_player::rendering::config::line::normal::main::Use;
	static constexpr auto value = enumerate(Plain, Syllable);
};

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONFIG_GLAZE_H_
