// clang-format off

// Generated by generate-config script. DO NOT EDIT.
// To change config, edit the schema and regenerate with generate-config script.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONFIG_GEN_H_

#include "rendering/config/container/index.gen.h"
#include "rendering/config/effect/index.gen.h"
#include "rendering/config/layout/index.gen.h"
#include "rendering/config/line/index.gen.h"
#include "rendering/config/scroll/index.gen.h"

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config {
	/**
	 * Renderer configuration.
	 */
	struct Root {
		/**
		 * Background fill and padding of the player.
		 */
		::music_lyric_player::rendering::config::container::Root container;
		/**
		 * Alignment and spacing between lyric lines.
		 */
		::music_lyric_player::rendering::config::layout::Root layout;
		/**
		 * Viewport scrolling and its transition animation.
		 */
		::music_lyric_player::rendering::config::scroll::Root scroll;
		/**
		 * Font and per-state colors of lyric lines.
		 */
		::music_lyric_player::rendering::config::line::Root line;
		/**
		 * Distance-from-focus scale and blur effects.
		 */
		::music_lyric_player::rendering::config::effect::Root effect;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.container, src.container, key);
			overlay(dst.layout, src.layout, key);
			overlay(dst.scroll, src.scroll, key);
			overlay(dst.line, src.line, key);
			overlay(dst.effect, src.effect, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.container, prev.container, next.container, key);
			capture(delta.layout, prev.layout, next.layout, key);
			capture(delta.scroll, prev.scroll, next.scroll, key);
			capture(delta.line, prev.line, next.line, key);
			capture(delta.effect, prev.effect, next.effect, key);
		}

		/**
		 * Resolves the accumulated overrides into a fully-concrete config: resets `out` to the defaults, overlays the overrides, then fills every leaf that was not explicitly set from its inherited source.
		 */
		friend void resolve(Root& out, const Root& overrides, ::music_lyric_player::utils::config::Access key) {
			out = Root{};
			overlay(out, overrides, key);
			if (!overrides.line.normal.main.syllable.font.family.assigned()) {
				out.line.normal.main.syllable.font.family = out.line.normal.base.font.family.value();
			}
			if (!overrides.line.normal.main.syllable.font.size.assigned()) {
				out.line.normal.main.syllable.font.size = out.line.normal.base.font.size.value();
			}
			if (!overrides.line.normal.main.syllable.style.normal.color.assigned()) {
				out.line.normal.main.syllable.style.normal.color = out.line.normal.base.style.normal.color.value();
			}
			if (!overrides.line.normal.main.syllable.style.normal.opacity.assigned()) {
				out.line.normal.main.syllable.style.normal.opacity = out.line.normal.base.style.normal.opacity.value();
			}
			if (!overrides.line.normal.main.syllable.style.active.color.assigned()) {
				out.line.normal.main.syllable.style.active.color = out.line.normal.base.style.active.color.value();
			}
			if (!overrides.line.normal.main.syllable.style.active.opacity.assigned()) {
				out.line.normal.main.syllable.style.active.opacity = out.line.normal.base.style.active.opacity.value();
			}
			if (!overrides.line.normal.main.syllable.style.played.color.assigned()) {
				out.line.normal.main.syllable.style.played.color = out.line.normal.base.style.played.color.value();
			}
			if (!overrides.line.normal.main.syllable.style.played.opacity.assigned()) {
				out.line.normal.main.syllable.style.played.opacity = out.line.normal.base.style.played.opacity.value();
			}
		}
	};

	/**
	 * Built-in defaults (every field at its schema default); the fallback when a config value fails to parse.
	 */
	inline const Root Default{};

} // namespace music_lyric_player::rendering::config

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONFIG_GEN_H_
