// Generated by generate-config script from config.schema.json. DO NOT EDIT.

/**
 * Timing-engine configuration.
 */
export interface PlaybackConfig {
  /**
   * Whether gaps in the active-line indices are filled so the active range stays contiguous.
   *
   * @default true
   */
  bridgeActive?: boolean;
  /**
   * Window in milliseconds within which consecutive lines cluster and deactivate together.
   *
   * @default 300.0
   */
  mergeWindow?: number;
  /**
   * Maximum number of lines in one merge batch; a value of 0 or less leaves it unbounded.
   *
   * @default 3
   */
  mergeLimit?: number;
  /**
   * Global layer of the three-layer lyric offset.
   */
  offset?: OffsetConfig;
}

/**
 * The global layer of the three-layer offset (global + meta + temp).
 */
export interface OffsetConfig {
  /**
   * Offset in milliseconds applied to every song.
   *
   * @default 0.0
   */
  global?: number;
  /**
   * Whether the lyric's own meta offset is applied on top of the global one.
   *
   * @default true
   */
  useMeta?: boolean;
  /**
   * Whether the temporary offset is cleared when a new lyric loads.
   *
   * @default true
   */
  resetTempOnLyricChange?: boolean;
}
