// Generated by generate-config script from config.schema.json. DO NOT EDIT.

export type LayoutAlign = "Left" | "Center" | "Right";

export type ScrollMode = "Smooth" | "Ripple" | "Directional" | "Stagger";

export type LineNormalMainUse = "Plain" | "Syllable";

/**
 * Renderer configuration.
 */
export interface RenderingConfig {
  /**
   * Background fill and padding of the player.
   */
  container?: ContainerConfig;
  /**
   * Alignment and spacing between lyric lines.
   */
  layout?: LayoutConfig;
  /**
   * Viewport scrolling and its transition animation.
   */
  scroll?: ScrollConfig;
  /**
   * Font and per-state colors of lyric lines.
   */
  line?: LineConfig;
  /**
   * Distance-from-focus scale and blur effects.
   */
  effect?: EffectConfig;
}

/**
 * Background fill and padding of the player.
 */
export interface ContainerConfig {
  /**
   * Background fill of the whole player.
   * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
   *
   * @default "#101014"
   * @example "#101014"
   * @example "rgb(16, 16, 20)"
   */
  backgroundColor?: string;
  /**
   * Horizontal padding on each side of the content.
   * A `%` value is relative to the viewport width.
   * A bare number or `px` is an absolute length in logical pixels.
   *
   * @default "48px"
   * @example 48
   * @example "48px"
   * @example "5%"
   */
  paddingX?: string;
  /**
   * Edge fade applied at the top and bottom of the player.
   */
  fade?: ContainerFadeConfig;
}

/**
 * Soft fade at the top and bottom edges of the player.
 *
 * Lines ease out as they approach the viewport edge.
 */
export interface ContainerFadeConfig {
  /**
   * Whether to enable the edge fade.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Top fade range.
   * A `%` value is relative to the viewport height.
   * A bare number or `px` is an absolute length in logical pixels.
   *
   * @default "5%"
   * @example "5%"
   * @example "24px"
   */
  top?: string;
  /**
   * Bottom fade range.
   * A `%` value is relative to the viewport height.
   * A bare number or `px` is an absolute length in logical pixels.
   *
   * @default "10%"
   * @example "10%"
   * @example "48px"
   */
  bottom?: string;
}

/**
 * Alignment and spacing applied to every lyric line.
 */
export interface LayoutConfig {
  /**
   * Horizontal alignment of lines within the container.
   *
   * @default "Left"
   */
  align?: LayoutAlign;
  /**
   * Vertical spacing between adjacent lines.
   * A `%` value is relative to the viewport height.
   * A bare number or `px` is an absolute length in logical pixels.
   *
   * @default "16px"
   * @example 16
   * @example "16px"
   * @example "2%"
   */
  gap?: string;
}

/**
 * Viewport scrolling that follows the active line.
 */
export interface ScrollConfig {
  /**
   * Vertical anchor of the active line inside the viewport, as a ratio of its height.
   *
   * - `0.5`: keep the active line at the vertical center
   * - `0.3`: keep the active line closer to the top
   *
   * @default 0.5
   * @minimum 0
   * @maximum 1
   */
  anchor?: number;
  /**
   * Transition animation used when the active line changes.
   */
  animation?: ScrollAnimationConfig;
}

/**
 * Transition animation used when the active line changes.
 */
export interface ScrollAnimationConfig {
  /**
   * Cascade mode distributing per-line transition delays.
   *
   * - `Smooth`: all lines move together, no cascade
   * - `Ripple`: symmetric cascade outward from the active line
   * - `Directional`: nonlinear cascade following the latest active-line movement direction
   * - `Stagger`: linear cascade following the latest active-line movement direction
   *
   * @default "Smooth"
   */
  mode?: ScrollMode;
  /**
   * Smooth mode parameters.
   */
  smooth?: ScrollSmoothConfig;
  /**
   * Ripple mode parameters.
   */
  ripple?: ScrollRippleConfig;
  /**
   * Directional mode parameters.
   */
  directional?: ScrollDirectionalConfig;
  /**
   * Stagger mode parameters.
   */
  stagger?: ScrollStaggerConfig;
}

/**
 * Parameters for the Smooth mode: a uniform, non-cascade transition.
 */
export interface ScrollSmoothConfig {
  /**
   * Transition duration of each individual line, in `ms`.
   * In cascade modes the total visual length is roughly `duration + maxDelay`.
   * `0` snaps to the target without easing.
   *
   * @default 500.0
   */
  duration?: number;
  /**
   * Easing curve for the transition.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "ease"
   * @example "ease-in-out"
   * @example "cubic-bezier(0.4, 0, 0.2, 1)"
   */
  easing?: string;
  /**
   * Fixed delay before the transition starts, in `ms`.
   *
   * @default 0.0
   */
  delay?: number;
}

/**
 * Parameters for the Ripple mode: a symmetric cascade radiating outward from the active line.
 */
export interface ScrollRippleConfig {
  /**
   * Transition duration of each individual line, in `ms`.
   * In cascade modes the total visual length is roughly `duration + maxDelay`.
   * `0` snaps to the target without easing.
   *
   * @default 500.0
   */
  duration?: number;
  /**
   * Easing curve for the transition.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "ease"
   * @example "ease-in-out"
   * @example "cubic-bezier(0.4, 0, 0.2, 1)"
   */
  easing?: string;
  /**
   * Offset (in line units) at which the per-line delay saturates.
   * Lines with `|offset| >= range` all receive the maximum delay.
   *
   * @default 5.0
   * @minimum 1
   */
  range?: number;
  /**
   * Delay increment per offset unit, in `ms`; scales the cascade curve.
   *
   * @default 40.0
   * @minimum 10
   */
  step?: number;
}

/**
 * Parameters for the Directional mode: a nonlinear cascade following the latest active-line movement direction.
 */
export interface ScrollDirectionalConfig {
  /**
   * Transition duration of each individual line, in `ms`.
   * In cascade modes the total visual length is roughly `duration + maxDelay`.
   * `0` snaps to the target without easing.
   *
   * @default 500.0
   */
  duration?: number;
  /**
   * Easing curve for the transition.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "ease"
   * @example "ease-in-out"
   * @example "cubic-bezier(0.4, 0, 0.2, 1)"
   */
  easing?: string;
  /**
   * Offset (in line units) at which the per-line delay saturates.
   *
   * @default 5.0
   * @minimum 1
   */
  range?: number;
  /**
   * Delay increment per offset unit, in `ms`.
   *
   * @default 40.0
   * @minimum 10
   */
  step?: number;
}

/**
 * Parameters for the Stagger mode: a linear cascade following the latest active-line movement direction.
 */
export interface ScrollStaggerConfig {
  /**
   * Transition duration of each individual line, in `ms`.
   * In cascade modes the total visual length is roughly `duration + maxDelay`.
   * `0` snaps to the target without easing.
   *
   * @default 500.0
   */
  duration?: number;
  /**
   * Easing curve for the transition.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "ease"
   * @example "ease-in-out"
   * @example "cubic-bezier(0.4, 0, 0.2, 1)"
   */
  easing?: string;
  /**
   * Offset (in line units) at which the delay saturates.
   *
   * @default 4.0
   * @minimum 1
   */
  range?: number;
  /**
   * Delay increment per offset unit, in `ms`.
   *
   * @default 50.0
   * @minimum 1
   */
  step?: number;
}

/**
 * Normal-line rendering and instrumental-gap indicators.
 */
export interface LineConfig {
  /**
   * Rendering settings of vocal lyric lines.
   */
  normal?: LineNormalConfig;
  /**
   * Instrumental-gap indicator geometry and animation styles.
   */
  interlude?: LineInterludeConfig;
}

/**
 * Rendering settings of vocal lyric lines.
 */
export interface LineNormalConfig {
  /**
   * Appearance shared by the main vocal line and its annotation sub-lines.
   */
  base?: LineNormalBase;
  /**
   * Rendering mode and settings of the main vocal content.
   */
  main?: LineNormalMainConfig;
  /**
   * Translation and romanization sub-lines beneath the main content.
   */
  annotation?: LineNormalAnnotationConfig;
}

/**
 * Appearance shared by the main vocal line and its annotation sub-lines.
 */
export interface LineNormalBase {
  /**
   * Preferred BCP-47 tag shared by the line and inherited by its annotation rows when they set none; used to choose among coexisting translations or romanizations.
   *
   * @default "zh-hans"
   */
  language?: string;
  /**
   * Font shared by every line.
   */
  font?: CommonFontConfig;
  /**
   * Inactive and active styles shared by normal lyric lines.
   */
  style?: CommonStateStyleConfig;
}

/**
 * Font appearance shared by lyric lines and their annotation sub-lines.
 */
export interface CommonFontConfig {
  /**
   * Font family name; empty uses the platform default.
   *
   * @example "PingFang SC"
   */
  family?: string;
  /**
   * Font size of the lyric lines.
   * A `%` value is relative to the parent line's font size (e.g. translation / background lines).
   * A bare number or `px` is an absolute length in logical pixels.
   *
   * @default "34px"
   * @example 34
   * @example "34px"
   * @example "80%"
   */
  size?: string;
}

/**
 * Inactive, active, and played styles shared by normal lyric lines and their annotation sub-lines.
 */
export interface CommonStateStyleConfig {
  /**
   * Style of inactive lines.
   */
  normal?: CommonStyleConfig;
  /**
   * Style of active lines.
   */
  active?: CommonStyleConfig;
  /**
   * Style of played lines that have already been sung.
   */
  played?: CommonStyleConfig;
}

/**
 * Visual style for a single render state.
 */
export interface CommonStyleConfig {
  /**
   * Color of the render state.
   * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
   *
   * @default "#000000"
   * @example "#fff"
   * @example "rgba(255, 255, 255, 0.8)"
   */
  color?: string;
  /**
   * Opacity of the render state in the [0, 1] range; 1 is fully opaque.
   *
   * @default 1.0
   * @minimum 0
   * @maximum 1
   */
  opacity?: number;
}

/**
 * Rendering mode and settings of a normal line's main content.
 */
export interface LineNormalMainConfig {
  /**
   * Preferred renderer; lyrics without word timing still fall back to plain text.
   *
   * @default "Syllable"
   */
  use?: LineNormalMainUse;
  /**
   * Word-timed karaoke rendering settings.
   */
  syllable?: LineNormalMainSyllableConfig;
}

/**
 * Word-timed karaoke rendering settings.
 */
export interface LineNormalMainSyllableConfig {
  /**
   * Font of the karaoke main content; inherits the base line font when unset.
   *
   * @see line.normal.base.font
   */
  font?: CommonFontConfig;
  /**
   * Inactive, active, and played styles of the karaoke main content; inherit the base line styles when unset.
   *
   * @see line.normal.base.style
   */
  style?: CommonStateStyleConfig;
  /**
   * Timed word rendering and animation settings.
   */
  word?: LineNormalMainSyllableWordConfig;
}

/**
 * Rendering settings of each timed word.
 */
export interface LineNormalMainSyllableWordConfig {
  /**
   * Float and reveal animations of the word.
   */
  animation?: LineNormalMainSyllableWordAnimationConfig;
}

/**
 * Animation settings of timed words.
 */
export interface LineNormalMainSyllableWordAnimationConfig {
  /**
   * Vertical word motion.
   */
  floating?: LineNormalMainSyllableFloatConfig;
  /**
   * Karaoke color reveal mask.
   */
  mask?: LineNormalMainSyllableMaskConfig;
  /**
   * Per-character emphasize effect of stressed words.
   */
  emphasize?: LineNormalMainSyllableEmphasizeConfig;
}

/**
 * Vertical motion applied to each timed word.
 */
export interface LineNormalMainSyllableFloatConfig {
  /**
   * Whether timed words float while they are sung.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Starting vertical offset in logical pixels.
   *
   * @default 0.0
   */
  from?: number;
  /**
   * Ending vertical offset in logical pixels.
   *
   * @default -2.0
   */
  to?: number;
}

/**
 * Left-to-right karaoke reveal mask.
 */
export interface LineNormalMainSyllableMaskConfig {
  /**
   * Whether active words reveal progressively instead of switching immediately.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Soft-edge sizing of the reveal boundary.
   */
  feather?: LineNormalMainSyllableMaskFeatherConfig;
}

/**
 * Soft-edge sizing of the karaoke reveal mask.
 */
export interface LineNormalMainSyllableMaskFeatherConfig {
  /**
   * Base feather width as a multiple of word height.
   *
   * @default 0.5
   * @minimum 0
   * @maximum 2
   */
  normal?: number;
  /**
   * Feather multiplier for the first word.
   *
   * @default 1.5
   * @minimum 0
   * @maximum 5
   */
  first?: number;
  /**
   * Feather multiplier for the last word.
   *
   * @default 0.5
   * @minimum 0
   * @maximum 5
   */
  last?: number;
}

/**
 * Per-character emphasize effect of stressed syllables; at least one sub-effect must be enabled for the per-character split to happen.
 */
export interface LineNormalMainSyllableEmphasizeConfig {
  /**
   * Master switch for the entire emphasize feature.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Sub-effects.
   */
  effects?: LineNormalMainSyllableEmphasizeEffectsConfig;
  /**
   * Minimum animation duration in milliseconds; shorter syllables still emphasize but their timeline lasts at least this long.
   *
   * @default 1000.0
   * @minimum 0
   */
  minDuration?: number;
  /**
   * Playback rate used to wind down an in-flight per-character animation when the line leaves the active state.
   *
   * @default 4.0
   * @minimum 1
   */
  disablePlaybackRate?: number;
}

/**
 * Independently togglable sub-effects that compose the emphasize animation.
 */
export interface LineNormalMainSyllableEmphasizeEffectsConfig {
  /**
   * Main per-character transform.
   */
  main?: LineNormalMainSyllableEmphasizeMainConfig;
  /**
   * Glow halo.
   */
  glow?: LineNormalMainSyllableEmphasizeGlowConfig;
  /**
   * Secondary float layer.
   */
  floating?: LineNormalMainSyllableEmphasizeFloatConfig;
}

/**
 * Core per-character transform of the emphasize effect: a scale pulse with an outward fan-out and an upward lift.
 */
export interface LineNormalMainSyllableEmphasizeMainConfig {
  /**
   * Whether the main transform animation runs.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Peak scale increment; the character's peak scale is `1 + scale * intensity`, where the intensity derives from the syllable's duration.
   *
   * @default 0.1
   * @minimum 0
   */
  scale?: number;
  /**
   * Peak outward horizontal shift per character in logical pixels; characters fan out from the word's center.
   *
   * @default 1.0
   * @minimum 0
   */
  offsetHorizontal?: number;
  /**
   * Peak upward vertical shift in logical pixels, applied uniformly to every character.
   *
   * @default 1.0
   * @minimum 0
   */
  offsetVertical?: number;
  /**
   * Easing applied from rest to the peak at the pulse midpoint.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "cubic-bezier(0.2, 0.4, 0.58, 1)"
   */
  easingRise?: string;
  /**
   * Easing applied from the peak back to rest.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "cubic-bezier(0.3, 0, 0.58, 1)"
   */
  easingFall?: string;
}

/**
 * Glow halo rendered behind emphasized characters; the only sub-effect that defaults to off because every character costs one blur per frame.
 */
export interface LineNormalMainSyllableEmphasizeGlowConfig {
  /**
   * Whether to render the glow.
   *
   * @default false
   */
  enabled?: boolean;
  /**
   * Glow color; an unparseable string silently disables the glow, acting as a soft kill switch.
   * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
   *
   * @default "#000000"
   */
  color?: string;
  /**
   * Easing applied from rest to the peak at the pulse midpoint.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "cubic-bezier(0.2, 0.4, 0.58, 1)"
   */
  easingRise?: string;
  /**
   * Easing applied from the peak back to rest.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "cubic-bezier(0.3, 0, 0.58, 1)"
   */
  easingFall?: string;
  /**
   * Maximum glow radius in logical pixels; the duration-derived intensity clamps it further so short syllables get a tighter halo.
   *
   * @default 9.0
   * @minimum 0
   */
  maxRadius?: number;
  /**
   * Peak glow alpha in the `[0, 1]` range.
   *
   * @default 1.0
   * @minimum 0
   * @maximum 1
   */
  maxAlpha?: number;
}

/**
 * Secondary bounce layered on top of the per-word float animation.
 */
export interface LineNormalMainSyllableEmphasizeFloatConfig {
  /**
   * Whether to enable the secondary float.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Float timing.
   */
  duration?: LineNormalMainSyllableEmphasizeFloatDurationConfig;
  /**
   * Peak upward displacement in logical pixels.
   *
   * @default 2.0
   * @minimum 0
   */
  amplitude?: number;
  /**
   * Easing applied to each half of the bounce.
   * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
   *
   * @default "cubic-bezier(0.45, 0, 0.55, 1)"
   */
  easing?: string;
  /**
   * Amplified float for background lines.
   */
  background?: LineNormalMainSyllableEmphasizeFloatBackgroundConfig;
}

/**
 * Timing controls of the secondary float layer.
 */
export interface LineNormalMainSyllableEmphasizeFloatDurationConfig {
  /**
   * Float duration as a multiple of the main emphasize duration; values above 1 make the float linger after the main effect settles.
   *
   * @default 1.4
   * @minimum 0
   */
  scale?: number;
  /**
   * Milliseconds the float starts before the main emphasize effect.
   *
   * @default 400.0
   * @minimum 0
   */
  lead?: number;
}

/**
 * Amplified float for background lines, layered on the emphasize float.
 */
export interface LineNormalMainSyllableEmphasizeFloatBackgroundConfig {
  /**
   * Whether background lines get an amplified float.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Float amplitude multiplier applied on background lines.
   *
   * @default 2.0
   * @minimum 0
   */
  scale?: number;
}

/**
 * Annotation sub-lines beneath the main vocal line.
 */
export interface LineNormalAnnotationConfig {
  /**
   * Master switch; when false both rows hide regardless of their own visible.
   *
   * @default true
   */
  visible?: boolean;
  /**
   * Shared base inherited by all annotation rows.
   */
  base?: LineNormalAnnotationBase;
  /**
   * Romanization row overrides.
   */
  roman?: LineNormalAnnotationRoman;
  /**
   * Translation row overrides.
   */
  translate?: LineNormalAnnotationTranslate;
}

/**
 * Appearance shared by the annotation sub-lines beneath the main vocal line.
 */
export interface LineNormalAnnotationBase {
  /**
   * Annotation font; the family inherits the normal-line base, while the explicit `%` size renders relative to that parent.
   *
   * @see line.normal.base.font
   */
  font?: CommonFontConfig;
  /**
   * Annotation state styles; colors inherit the normal-line base, while explicit dimmer opacities let the rows recede beneath it.
   *
   * @see line.normal.base.style
   */
  style?: CommonStateStyleConfig;
}

/**
 * Romanization sub-line.
 */
export interface LineNormalAnnotationRoman {
  /**
   * Whether the romanization row shows.
   *
   * @default true
   */
  visible?: boolean;
  /**
   * Preferred BCP-47 tag for the romanization; inherits the line base when left empty.
   *
   * @default ""
   * @see line.normal.base.language
   */
  language?: string;
  /**
   * Row font; inherits the annotation base when unset.
   *
   * @see line.normal.annotation.base.font
   */
  font?: CommonFontConfig;
  /**
   * Row styles; inherit the annotation base when unset.
   *
   * @see line.normal.annotation.base.style
   */
  style?: CommonStateStyleConfig;
}

/**
 * Translation sub-line.
 */
export interface LineNormalAnnotationTranslate {
  /**
   * Whether the translation row shows.
   *
   * @default true
   */
  visible?: boolean;
  /**
   * Preferred BCP-47 tag for the translation; inherits the line base when left empty.
   *
   * @default ""
   * @see line.normal.base.language
   */
  language?: string;
  /**
   * Row font; inherits the annotation base when unset.
   *
   * @see line.normal.annotation.base.font
   */
  font?: CommonFontConfig;
  /**
   * Row styles; inherit the annotation base when unset.
   *
   * @see line.normal.annotation.base.style
   */
  style?: CommonStateStyleConfig;
}

/**
 * Geometry and state styles of instrumental-gap indicators.
 */
export interface LineInterludeConfig {
  /**
   * Diameter of each indicator dot.
   * A bare number or `px` is an absolute length in logical pixels.
   *
   * @default "16px"
   * @example 16
   * @example "16px"
   */
  size?: string;
  /**
   * Inactive and active dot styles.
   */
  style?: LineInterludeStateConfig;
}

/**
 * Inactive and active styles of an interlude indicator.
 */
export interface LineInterludeStateConfig {
  /**
   * Style before and after the interlude is active.
   */
  normal?: LineInterludeStyleConfig;
  /**
   * Style progressively filled while the interlude is active.
   */
  active?: LineInterludeStyleConfig;
}

/**
 * Visual style for one playback state of an interlude indicator.
 */
export interface LineInterludeStyleConfig {
  /**
   * Dot color for this playback state.
   * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
   *
   * @default "#ffffff"
   * @example "#fff"
   * @example "rgba(255, 255, 255, 0.8)"
   */
  color?: string;
  /**
   * Dot opacity for this playback state.
   *
   * @default 1.0
   * @minimum 0
   * @maximum 1
   */
  opacity?: number;
}

/**
 * Visual effects whose intensity depends on distance from the active line.
 *
 * Lines closer to the active one keep their natural look; lines farther away progressively shrink and/or blur.
 */
export interface EffectConfig {
  /**
   * Scale (zoom) effect: shrinks lines farther from the active one.
   */
  scale?: EffectScaleConfig;
  /**
   * Blur effect: blurs lines farther from the active one.
   */
  blur?: EffectBlurConfig;
}

/**
 * Scale (zoom) effect applied per line.
 *
 * The active line uses `max`; the farthest lines collapse to `min`.
 */
export interface EffectScaleConfig {
  /**
   * Whether to enable the scale effect.
   *
   * @default false
   */
  enabled?: boolean;
  /**
   * Scale ratio of the farthest line.
   *
   * @default 0.65
   */
  min?: number;
  /**
   * Scale ratio of the active line.
   *
   * @default 1.0
   */
  max?: number;
}

/**
 * Blur effect applied per line.
 *
 * The active line uses `min` (sharpest); the farthest lines reach `max` (most blurred).
 */
export interface EffectBlurConfig {
  /**
   * Whether to enable the blur effect.
   *
   * @default true
   */
  enabled?: boolean;
  /**
   * Blur radius of the active line in `px`, which is the sharpest state.
   *
   * @default 0.4
   */
  min?: number;
  /**
   * Blur radius of the farthest line in `px`, which is the most blurred state.
   *
   * @default 4.5
   */
  max?: number;
}
