// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LAYOUT_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LAYOUT_CONFIG_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_player::rendering::config::layout {
	/**
	 * Horizontal alignment of a line within the container.
	 */
	enum class Align {
		Left,
		Center,
		Right,
	};

	/**
	 * Alignment and spacing applied to every lyric line.
	 */
	struct Root {
		/**
		 * Horizontal alignment of lines within the container.
		 *
		 * @default Align::Left
		 */
		Align align = Align::Left;
		/**
		 * Vertical spacing between adjacent lines.
		 * A `%` value is relative to the viewport height.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "16px"
		 * @example 16
		 * @example "16px"
		 * @example "2%"
		 */
		::std::string gap = "16px";
	};

	struct RootPatch {
		::std::optional<Align> align;
		::std::optional<::std::string> gap;
	};

	struct RootChange {
		bool align = false;
		bool gap = false;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.align.has_value()) {
			cfg.align = *patch.align;
		}
		if (patch.gap.has_value()) {
			cfg.gap = *patch.gap;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.align = prev.align != next.align;
		change.gap = prev.gap != next.gap;
		change.any = change.align || change.gap;
		return change;
	}

} // namespace music_lyric_player::rendering::config::layout

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LAYOUT_CONFIG_GEN_H_
