// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LAYOUT_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LAYOUT_CONFIG_GEN_H_

#include <string>

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::layout {
	/**
	 * Horizontal alignment of a line within the container.
	 */
	enum class Align {
		Left,
		Center,
		Right,
	};

	/**
	 * Alignment and spacing applied to every lyric line.
	 */
	struct Root {
		/**
		 * Horizontal alignment of lines within the container.
		 *
		 * @default Align::Left
		 */
		::music_lyric_player::utils::config::Property<Align> align = Align::Left;
		/**
		 * Vertical spacing between adjacent lines.
		 * A `%` value is relative to the viewport height.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "16px"
		 * @example 16
		 * @example "16px"
		 * @example "2%"
		 */
		::music_lyric_player::utils::config::Property<::std::string> gap = "16px";

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.align.assigned()) dst.align = src.align.value();
			if (src.gap.assigned()) dst.gap = src.gap.value();
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.align == next.align)) delta.align = next.align.value();
			if (!(prev.gap == next.gap)) delta.gap = next.gap.value();
		}
	};

} // namespace music_lyric_player::rendering::config::layout

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LAYOUT_CONFIG_GEN_H_
