// clang-format off

// Generated by generate-config script. DO NOT EDIT.
// To change config, edit the schema and regenerate with generate-config script.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_EFFECT_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_EFFECT_CONFIG_GEN_H_

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::effect {
	/**
	 * Scale (zoom) effect applied per line.
	 *
	 * The active line uses `max`; the farthest lines collapse to `min`.
	 */
	struct ScaleConfig {
		/**
		 * Whether to enable the scale effect.
		 *
		 * @default false
		 */
		::music_lyric_player::utils::config::Property<bool> enabled = false;
		/**
		 * Scale ratio of the farthest line.
		 *
		 * @default 0.65
		 */
		::music_lyric_player::utils::config::Property<double> min = 0.65;
		/**
		 * Scale ratio of the active line.
		 *
		 * @default 1.0
		 */
		::music_lyric_player::utils::config::Property<double> max = 1.0;

		bool operator==(const ScaleConfig&) const = default;

		friend void overlay(ScaleConfig& dst, const ScaleConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.enabled.assigned()) dst.enabled = src.enabled.value();
			if (src.min.assigned()) dst.min = src.min.value();
			if (src.max.assigned()) dst.max = src.max.value();
		}

		friend void capture(ScaleConfig& delta, const ScaleConfig& prev, const ScaleConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.enabled == next.enabled)) delta.enabled = next.enabled.value();
			if (!(prev.min == next.min)) delta.min = next.min.value();
			if (!(prev.max == next.max)) delta.max = next.max.value();
		}
	};

	/**
	 * Blur effect applied per line.
	 *
	 * The active line uses `min` (sharpest); the farthest lines reach `max` (most blurred).
	 */
	struct BlurConfig {
		/**
		 * Whether to enable the blur effect.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> enabled = true;
		/**
		 * Blur radius of the active line, in `px` — the sharpest state.
		 *
		 * @default 0.4
		 */
		::music_lyric_player::utils::config::Property<double> min = 0.4;
		/**
		 * Blur radius of the farthest line, in `px` — the most blurred state.
		 *
		 * @default 4.5
		 */
		::music_lyric_player::utils::config::Property<double> max = 4.5;

		bool operator==(const BlurConfig&) const = default;

		friend void overlay(BlurConfig& dst, const BlurConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.enabled.assigned()) dst.enabled = src.enabled.value();
			if (src.min.assigned()) dst.min = src.min.value();
			if (src.max.assigned()) dst.max = src.max.value();
		}

		friend void capture(BlurConfig& delta, const BlurConfig& prev, const BlurConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.enabled == next.enabled)) delta.enabled = next.enabled.value();
			if (!(prev.min == next.min)) delta.min = next.min.value();
			if (!(prev.max == next.max)) delta.max = next.max.value();
		}
	};

	/**
	 * Visual effects whose intensity depends on distance from the active line.
	 *
	 * Lines closer to the active one keep their natural look; lines farther away progressively shrink and/or blur.
	 */
	struct Root {
		/**
		 * Scale (zoom) effect: shrinks lines farther from the active one.
		 */
		ScaleConfig scale;
		/**
		 * Blur effect: blurs lines farther from the active one.
		 */
		BlurConfig blur;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.scale, src.scale, key);
			overlay(dst.blur, src.blur, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.scale, prev.scale, next.scale, key);
			capture(delta.blur, prev.blur, next.blur, key);
		}
	};

} // namespace music_lyric_player::rendering::config::effect

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_EFFECT_CONFIG_GEN_H_
