// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_EFFECT_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_EFFECT_CONFIG_GEN_H_

#include <optional>

namespace music_lyric_player::rendering::config::effect {
	/**
	 * Scale (zoom) effect applied per line.
	 *
	 * The active line uses `max`; the farthest lines collapse to `min`.
	 */
	struct ScaleConfig {
		/**
		 * Whether to enable the scale effect.
		 *
		 * @default false
		 */
		bool enabled = false;
		/**
		 * Scale ratio of the farthest line.
		 *
		 * @default 0.65
		 */
		double min = 0.65;
		/**
		 * Scale ratio of the active line.
		 *
		 * @default 1.0
		 */
		double max = 1.0;
	};

	/**
	 * Blur effect applied per line.
	 *
	 * The active line uses `min` (sharpest); the farthest lines reach `max` (most blurred).
	 */
	struct BlurConfig {
		/**
		 * Whether to enable the blur effect.
		 *
		 * @default true
		 */
		bool enabled = true;
		/**
		 * Blur radius of the active line, in `px` — the sharpest state.
		 *
		 * @default 0.4
		 */
		double min = 0.4;
		/**
		 * Blur radius of the farthest line, in `px` — the most blurred state.
		 *
		 * @default 4.5
		 */
		double max = 4.5;
	};

	/**
	 * Visual effects whose intensity depends on distance from the active line.
	 *
	 * Lines closer to the active one keep their natural look; lines farther away progressively shrink and/or blur.
	 */
	struct Root {
		/**
		 * Scale (zoom) effect: shrinks lines farther from the active one.
		 */
		ScaleConfig scale;
		/**
		 * Blur effect: blurs lines farther from the active one.
		 */
		BlurConfig blur;
	};

	struct ScaleConfigPatch {
		::std::optional<bool> enabled;
		::std::optional<double> min;
		::std::optional<double> max;
	};

	struct BlurConfigPatch {
		::std::optional<bool> enabled;
		::std::optional<double> min;
		::std::optional<double> max;
	};

	struct RootPatch {
		ScaleConfigPatch scale;
		BlurConfigPatch blur;
	};

	struct ScaleConfigChange {
		bool enabled = false;
		bool min = false;
		bool max = false;
		bool any = false;
	};

	struct BlurConfigChange {
		bool enabled = false;
		bool min = false;
		bool max = false;
		bool any = false;
	};

	struct RootChange {
		ScaleConfigChange scale;
		BlurConfigChange blur;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(ScaleConfig& cfg, const ScaleConfigPatch& patch) {
		if (patch.enabled.has_value()) {
			cfg.enabled = *patch.enabled;
		}
		if (patch.min.has_value()) {
			cfg.min = *patch.min;
		}
		if (patch.max.has_value()) {
			cfg.max = *patch.max;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(BlurConfig& cfg, const BlurConfigPatch& patch) {
		if (patch.enabled.has_value()) {
			cfg.enabled = *patch.enabled;
		}
		if (patch.min.has_value()) {
			cfg.min = *patch.min;
		}
		if (patch.max.has_value()) {
			cfg.max = *patch.max;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.scale, patch.scale);
		apply(cfg.blur, patch.blur);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline ScaleConfigChange diff(const ScaleConfig& prev, const ScaleConfig& next) {
		ScaleConfigChange change;
		change.enabled = prev.enabled != next.enabled;
		change.min = prev.min != next.min;
		change.max = prev.max != next.max;
		change.any = change.enabled || change.min || change.max;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline BlurConfigChange diff(const BlurConfig& prev, const BlurConfig& next) {
		BlurConfigChange change;
		change.enabled = prev.enabled != next.enabled;
		change.min = prev.min != next.min;
		change.max = prev.max != next.max;
		change.any = change.enabled || change.min || change.max;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.scale = diff(prev.scale, next.scale);
		change.blur = diff(prev.blur, next.blur);
		change.any = change.scale.any || change.blur.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::effect

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_EFFECT_CONFIG_GEN_H_
