// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_COMMON_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_COMMON_CONFIG_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_player::rendering::config::common {
	/**
	 * Font appearance shared by lyric lines and their annotation sub-lines.
	 */
	struct FontConfig {
		/**
		 * Font family name; empty uses the platform default.
		 *
		 * @example "PingFang SC"
		 */
		::std::string family = {};
		/**
		 * Font size of the lyric lines.
		 * A `%` value is relative to the parent line's font size (e.g. translation / background lines).
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "34px"
		 * @example 34
		 * @example "34px"
		 * @example "80%"
		 */
		::std::string size = "34px";
	};

	/**
	 * Visual style for a single render state.
	 */
	struct StyleConfig {
		/**
		 * Color of the render state.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#000000"
		 * @example "#fff"
		 * @example "rgba(255, 255, 255, 0.8)"
		 */
		::std::string color = "#000000";
		/**
		 * Opacity of the render state in the [0, 1] range; 1 is fully opaque.
		 *
		 * @default 1.0
		 * @minimum 0
		 * @maximum 1
		 */
		double opacity = 1.0;
	};

	/**
	 * Inactive and active styles shared by normal lyric lines and their annotation sub-lines.
	 */
	struct StateStyleConfig {
		/**
		 * Style of inactive lines.
		 */
		StyleConfig normal = StyleConfig{ .color = "#ffffff", .opacity = 0.6 };
		/**
		 * Style of active lines.
		 */
		StyleConfig active = StyleConfig{ .color = "#ffffff", .opacity = 1.0 };
	};

	struct FontConfigPatch {
		::std::optional<::std::string> family;
		::std::optional<::std::string> size;
	};

	struct StyleConfigPatch {
		::std::optional<::std::string> color;
		::std::optional<double> opacity;
	};

	struct StateStyleConfigPatch {
		StyleConfigPatch normal;
		StyleConfigPatch active;
	};

	struct FontConfigChange {
		bool family = false;
		bool size = false;
		bool any = false;
	};

	struct StyleConfigChange {
		bool color = false;
		bool opacity = false;
		bool any = false;
	};

	struct StateStyleConfigChange {
		StyleConfigChange normal;
		StyleConfigChange active;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(FontConfig& cfg, const FontConfigPatch& patch) {
		if (patch.family.has_value()) {
			cfg.family = *patch.family;
		}
		if (patch.size.has_value()) {
			cfg.size = *patch.size;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(StyleConfig& cfg, const StyleConfigPatch& patch) {
		if (patch.color.has_value()) {
			cfg.color = *patch.color;
		}
		if (patch.opacity.has_value()) {
			cfg.opacity = *patch.opacity;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(StateStyleConfig& cfg, const StateStyleConfigPatch& patch) {
		apply(cfg.normal, patch.normal);
		apply(cfg.active, patch.active);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline FontConfigChange diff(const FontConfig& prev, const FontConfig& next) {
		FontConfigChange change;
		change.family = prev.family != next.family;
		change.size = prev.size != next.size;
		change.any = change.family || change.size;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline StyleConfigChange diff(const StyleConfig& prev, const StyleConfig& next) {
		StyleConfigChange change;
		change.color = prev.color != next.color;
		change.opacity = prev.opacity != next.opacity;
		change.any = change.color || change.opacity;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline StateStyleConfigChange diff(const StateStyleConfig& prev, const StateStyleConfig& next) {
		StateStyleConfigChange change;
		change.normal = diff(prev.normal, next.normal);
		change.active = diff(prev.active, next.active);
		change.any = change.normal.any || change.active.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::common

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_COMMON_CONFIG_GEN_H_
