// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_COMMON_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_COMMON_CONFIG_GEN_H_

#include <string>

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::common {
	/**
	 * Font appearance shared by lyric lines and their annotation sub-lines.
	 */
	struct FontConfig {
		/**
		 * Font family name; empty uses the platform default.
		 *
		 * @example "PingFang SC"
		 */
		::music_lyric_player::utils::config::Property<::std::string> family = {};
		/**
		 * Font size of the lyric lines.
		 * A `%` value is relative to the parent line's font size (e.g. translation / background lines).
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "34px"
		 * @example 34
		 * @example "34px"
		 * @example "80%"
		 */
		::music_lyric_player::utils::config::Property<::std::string> size = "34px";

		bool operator==(const FontConfig&) const = default;

		friend void overlay(FontConfig& dst, const FontConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.family.assigned()) dst.family = src.family.value();
			if (src.size.assigned()) dst.size = src.size.value();
		}

		friend void capture(FontConfig& delta, const FontConfig& prev, const FontConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.family == next.family)) delta.family = next.family.value();
			if (!(prev.size == next.size)) delta.size = next.size.value();
		}
	};

	/**
	 * Visual style for a single render state.
	 */
	struct StyleConfig {
		/**
		 * Color of the render state.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#000000"
		 * @example "#fff"
		 * @example "rgba(255, 255, 255, 0.8)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> color = "#000000";
		/**
		 * Opacity of the render state in the [0, 1] range; 1 is fully opaque.
		 *
		 * @default 1.0
		 * @minimum 0
		 * @maximum 1
		 */
		::music_lyric_player::utils::config::Property<double> opacity = 1.0;

		bool operator==(const StyleConfig&) const = default;

		friend void overlay(StyleConfig& dst, const StyleConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.color.assigned()) dst.color = src.color.value();
			if (src.opacity.assigned()) dst.opacity = src.opacity.value();
		}

		friend void capture(StyleConfig& delta, const StyleConfig& prev, const StyleConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.color == next.color)) delta.color = next.color.value();
			if (!(prev.opacity == next.opacity)) delta.opacity = next.opacity.value();
		}
	};

	/**
	 * Inactive, active, and played styles shared by normal lyric lines and their annotation sub-lines.
	 */
	struct StateStyleConfig {
		/**
		 * Style of inactive lines.
		 */
		StyleConfig normal = StyleConfig{ .color = "#ffffff", .opacity = 0.6 };
		/**
		 * Style of active lines.
		 */
		StyleConfig active = StyleConfig{ .color = "#ffffff", .opacity = 1.0 };
		/**
		 * Style of played lines that have already been sung.
		 */
		StyleConfig played = StyleConfig{ .color = "#ffffff", .opacity = 0.4 };

		bool operator==(const StateStyleConfig&) const = default;

		friend void overlay(StateStyleConfig& dst, const StateStyleConfig& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.normal, src.normal, key);
			overlay(dst.active, src.active, key);
			overlay(dst.played, src.played, key);
		}

		friend void capture(StateStyleConfig& delta, const StateStyleConfig& prev, const StateStyleConfig& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.normal, prev.normal, next.normal, key);
			capture(delta.active, prev.active, next.active, key);
			capture(delta.played, prev.played, next.played, key);
		}
	};

} // namespace music_lyric_player::rendering::config::common

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_COMMON_CONFIG_GEN_H_
