// clang-format off
// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"
#include "render/config/common/index.gen.h"

namespace music_lyric_player::render::config::line {
	/**
	 * Font and per-state colors of lyric lines.
	 */
	struct Root {
		/**
		 * Font shared by every line.
		 */
		::music_lyric_player::render::config::common::FontConfig font;
		/**
		 * Style of inactive lines (default color `rgba(255, 255, 255, 0.4)`).
		 */
		::music_lyric_player::render::config::common::StyleConfig normal = ::music_lyric_player::render::config::common::StyleConfig{ .color = "rgba(255, 255, 255, 0.4)" };
		/**
		 * Style of the active line (default color `#ffffff`).
		 */
		::music_lyric_player::render::config::common::StyleConfig active = ::music_lyric_player::render::config::common::StyleConfig{ .color = "#ffffff" };
	};

	struct RootPatch {
		::music_lyric_player::render::config::common::FontConfigPatch font;
		::music_lyric_player::render::config::common::StyleConfigPatch normal;
		::music_lyric_player::render::config::common::StyleConfigPatch active;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Root& cfg, const RootPatch& patch) {
		applyConfigPatch(cfg.font, patch.font);
		applyConfigPatch(cfg.normal, patch.normal);
		applyConfigPatch(cfg.active, patch.active);
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Root& prev, const Root& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.font, next.font, prefix + "font" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "font");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.normal, next.normal, prefix + "normal" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "normal");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.active, next.active, prefix + "active" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "active");
			}
		}
	}

	namespace RootKeys {
		namespace font {
			inline constexpr ::std::string_view family{"font.family"};
			inline constexpr ::std::string_view size{"font.size"};
		} // namespace font
		namespace normal {
			inline constexpr ::std::string_view color{"normal.color"};
		} // namespace normal
		namespace active {
			inline constexpr ::std::string_view color{"active.color"};
		} // namespace active
	} // namespace RootKeys

} // namespace music_lyric_player::render::config::line

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_
// clang-format on
