// clang-format off
// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"

namespace music_lyric_player::render::config::line {
	/**
	 * Font appearance shared by every lyric line.
	 */
	struct FontConfig {
		/**
		 * Font family name; empty uses the platform default.
		 *
		 * @default ""
		 * @example "PingFang SC"
		 */
		::std::string family = {};
		/**
		 * Font size; a bare number or `px` is absolute.
		 * `%` is relative to the parent line's font size (e.g. translation / background lines).
		 *
		 * @default "34px"
		 * @example 34
		 * @example "34px"
		 * @example "80%"
		 */
		::std::string size = "34px";
	};

	/**
	 * Style of inactive lines.
	 */
	struct NormalConfig {
		/**
		 * ARGB color of inactive lines.
		 * @default 0x66ffffffu
		 */
		unsigned int color = 0x66ffffffu;
	};

	/**
	 * Style of the active line.
	 */
	struct ActiveConfig {
		/**
		 * ARGB color of the active line.
		 * @default 0xffffffffu
		 */
		unsigned int color = 0xffffffffu;
	};

	/**
	 * Font and per-state colors of lyric lines.
	 */
	struct Root {
		/**
		 * Font shared by every line.
		 */
		FontConfig font;
		/**
		 * Style of inactive lines.
		 */
		NormalConfig normal;
		/**
		 * Style of the active line.
		 */
		ActiveConfig active;
	};

	struct FontConfigPatch {
		::std::optional<::std::string> family;
		::std::optional<::std::string> size;
	};

	struct NormalConfigPatch {
		::std::optional<unsigned int> color;
	};

	struct ActiveConfigPatch {
		::std::optional<unsigned int> color;
	};

	struct RootPatch {
		FontConfigPatch font;
		NormalConfigPatch normal;
		ActiveConfigPatch active;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(FontConfig& cfg, const FontConfigPatch& patch) {
		if (patch.family.has_value()) {
			cfg.family = *patch.family;
		}
		if (patch.size.has_value()) {
			cfg.size = *patch.size;
		}
	}

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(NormalConfig& cfg, const NormalConfigPatch& patch) {
		if (patch.color.has_value()) {
			cfg.color = *patch.color;
		}
	}

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(ActiveConfig& cfg, const ActiveConfigPatch& patch) {
		if (patch.color.has_value()) {
			cfg.color = *patch.color;
		}
	}

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Root& cfg, const RootPatch& patch) {
		applyConfigPatch(cfg.font, patch.font);
		applyConfigPatch(cfg.normal, patch.normal);
		applyConfigPatch(cfg.active, patch.active);
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const FontConfig& prev, const FontConfig& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.family != next.family) {
			keys.insert(prefix + "family");
		}
		if (prev.size != next.size) {
			keys.insert(prefix + "size");
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const NormalConfig& prev, const NormalConfig& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.color != next.color) {
			keys.insert(prefix + "color");
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const ActiveConfig& prev, const ActiveConfig& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.color != next.color) {
			keys.insert(prefix + "color");
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Root& prev, const Root& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.font, next.font, prefix + "font" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "font");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.normal, next.normal, prefix + "normal" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "normal");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.active, next.active, prefix + "active" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "active");
			}
		}
	}

	namespace FontConfigKeys {
		inline constexpr ::std::string_view family{"family"};
		inline constexpr ::std::string_view size{"size"};
	} // namespace FontConfigKeys

	namespace NormalConfigKeys {
		inline constexpr ::std::string_view color{"color"};
	} // namespace NormalConfigKeys

	namespace ActiveConfigKeys {
		inline constexpr ::std::string_view color{"color"};
	} // namespace ActiveConfigKeys

	namespace RootKeys {
		namespace font {
			inline constexpr ::std::string_view family{"font.family"};
			inline constexpr ::std::string_view size{"font.size"};
		} // namespace font
		namespace normal {
			inline constexpr ::std::string_view color{"normal.color"};
		} // namespace normal
		namespace active {
			inline constexpr ::std::string_view color{"active.color"};
		} // namespace active
	} // namespace RootKeys

} // namespace music_lyric_player::render::config::line

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_
// clang-format on
