// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_

#include "render/config/common/index.gen.h"

namespace music_lyric_player::render::config::line {
	/**
	 * Font and per-state colors of lyric lines.
	 */
	struct Root {
		/**
		 * Font shared by every line.
		 */
		::music_lyric_player::render::config::common::FontConfig font;
		/**
		 * Style of inactive lines (default color `rgba(255, 255, 255, 0.4)`).
		 */
		::music_lyric_player::render::config::common::StyleConfig normal = ::music_lyric_player::render::config::common::StyleConfig{ .color = "rgba(255, 255, 255, 0.4)" };
		/**
		 * Style of the active line (default color `#ffffff`).
		 */
		::music_lyric_player::render::config::common::StyleConfig active = ::music_lyric_player::render::config::common::StyleConfig{ .color = "#ffffff" };
	};

	struct RootPatch {
		::music_lyric_player::render::config::common::FontConfigPatch font;
		::music_lyric_player::render::config::common::StyleConfigPatch normal;
		::music_lyric_player::render::config::common::StyleConfigPatch active;
	};

	struct RootChange {
		::music_lyric_player::render::config::common::FontConfigChange font;
		::music_lyric_player::render::config::common::StyleConfigChange normal;
		::music_lyric_player::render::config::common::StyleConfigChange active;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.font, patch.font);
		apply(cfg.normal, patch.normal);
		apply(cfg.active, patch.active);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.font = diff(prev.font, next.font);
		change.normal = diff(prev.normal, next.normal);
		change.active = diff(prev.active, next.active);
		change.any = change.font.any || change.normal.any || change.active.any;
		return change;
	}

} // namespace music_lyric_player::render::config::line

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_CONFIG_GEN_H_
