// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_SCROLL_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_SCROLL_CONFIG_GEN_H_

#include <string>

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::scroll {
	/**
	 * Scroll cascade mode selecting how per-line transition delays are distributed.
	 */
	enum class Mode {
		Smooth,
		Ripple,
		Directional,
		Stagger,
	};

	/**
	 * Parameters for the Smooth mode: a uniform, non-cascade transition.
	 */
	struct SmoothConfig {
		/**
		 * Transition duration of each individual line, in `ms`.
		 * In cascade modes the total visual length is roughly `duration + maxDelay`.
		 * `0` snaps to the target without easing.
		 *
		 * @default 500.0
		 */
		::music_lyric_player::utils::config::Property<double> duration = 500.0;
		/**
		 * Easing curve for the transition.
		 * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
		 *
		 * @default "ease"
		 * @example "ease-in-out"
		 * @example "cubic-bezier(0.4, 0, 0.2, 1)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> easing = "ease";
		/**
		 * Fixed delay before the transition starts, in `ms`.
		 *
		 * @default 0.0
		 */
		::music_lyric_player::utils::config::Property<double> delay = 0.0;

		bool operator==(const SmoothConfig&) const = default;

		friend void overlay(SmoothConfig& dst, const SmoothConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.duration.assigned()) dst.duration = src.duration.value();
			if (src.easing.assigned()) dst.easing = src.easing.value();
			if (src.delay.assigned()) dst.delay = src.delay.value();
		}

		friend void capture(SmoothConfig& delta, const SmoothConfig& prev, const SmoothConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.duration == next.duration)) delta.duration = next.duration.value();
			if (!(prev.easing == next.easing)) delta.easing = next.easing.value();
			if (!(prev.delay == next.delay)) delta.delay = next.delay.value();
		}
	};

	/**
	 * Parameters for the Ripple mode: a symmetric cascade radiating outward from the active line.
	 */
	struct RippleConfig {
		/**
		 * Transition duration of each individual line, in `ms`.
		 * In cascade modes the total visual length is roughly `duration + maxDelay`.
		 * `0` snaps to the target without easing.
		 *
		 * @default 500.0
		 */
		::music_lyric_player::utils::config::Property<double> duration = 500.0;
		/**
		 * Easing curve for the transition.
		 * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
		 *
		 * @default "ease"
		 * @example "ease-in-out"
		 * @example "cubic-bezier(0.4, 0, 0.2, 1)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> easing = "ease";
		/**
		 * Offset (in line units) at which the per-line delay saturates.
		 * Lines with `|offset| >= range` all receive the maximum delay.
		 *
		 * @default 5.0
		 * @minimum 1
		 */
		::music_lyric_player::utils::config::Property<double> range = 5.0;
		/**
		 * Delay increment per offset unit, in `ms`; scales the cascade curve.
		 *
		 * @default 40.0
		 * @minimum 10
		 */
		::music_lyric_player::utils::config::Property<double> step = 40.0;

		bool operator==(const RippleConfig&) const = default;

		friend void overlay(RippleConfig& dst, const RippleConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.duration.assigned()) dst.duration = src.duration.value();
			if (src.easing.assigned()) dst.easing = src.easing.value();
			if (src.range.assigned()) dst.range = src.range.value();
			if (src.step.assigned()) dst.step = src.step.value();
		}

		friend void capture(RippleConfig& delta, const RippleConfig& prev, const RippleConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.duration == next.duration)) delta.duration = next.duration.value();
			if (!(prev.easing == next.easing)) delta.easing = next.easing.value();
			if (!(prev.range == next.range)) delta.range = next.range.value();
			if (!(prev.step == next.step)) delta.step = next.step.value();
		}
	};

	/**
	 * Parameters for the Directional mode: a nonlinear cascade following the latest active-line movement direction.
	 */
	struct DirectionalConfig {
		/**
		 * Transition duration of each individual line, in `ms`.
		 * In cascade modes the total visual length is roughly `duration + maxDelay`.
		 * `0` snaps to the target without easing.
		 *
		 * @default 500.0
		 */
		::music_lyric_player::utils::config::Property<double> duration = 500.0;
		/**
		 * Easing curve for the transition.
		 * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
		 *
		 * @default "ease"
		 * @example "ease-in-out"
		 * @example "cubic-bezier(0.4, 0, 0.2, 1)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> easing = "ease";
		/**
		 * Offset (in line units) at which the per-line delay saturates.
		 *
		 * @default 5.0
		 * @minimum 1
		 */
		::music_lyric_player::utils::config::Property<double> range = 5.0;
		/**
		 * Delay increment per offset unit, in `ms`.
		 *
		 * @default 40.0
		 * @minimum 10
		 */
		::music_lyric_player::utils::config::Property<double> step = 40.0;

		bool operator==(const DirectionalConfig&) const = default;

		friend void overlay(DirectionalConfig& dst, const DirectionalConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.duration.assigned()) dst.duration = src.duration.value();
			if (src.easing.assigned()) dst.easing = src.easing.value();
			if (src.range.assigned()) dst.range = src.range.value();
			if (src.step.assigned()) dst.step = src.step.value();
		}

		friend void capture(DirectionalConfig& delta, const DirectionalConfig& prev, const DirectionalConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.duration == next.duration)) delta.duration = next.duration.value();
			if (!(prev.easing == next.easing)) delta.easing = next.easing.value();
			if (!(prev.range == next.range)) delta.range = next.range.value();
			if (!(prev.step == next.step)) delta.step = next.step.value();
		}
	};

	/**
	 * Parameters for the Stagger mode: a linear cascade following the latest active-line movement direction.
	 */
	struct StaggerConfig {
		/**
		 * Transition duration of each individual line, in `ms`.
		 * In cascade modes the total visual length is roughly `duration + maxDelay`.
		 * `0` snaps to the target without easing.
		 *
		 * @default 500.0
		 */
		::music_lyric_player::utils::config::Property<double> duration = 500.0;
		/**
		 * Easing curve for the transition.
		 * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
		 *
		 * @default "ease"
		 * @example "ease-in-out"
		 * @example "cubic-bezier(0.4, 0, 0.2, 1)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> easing = "ease";
		/**
		 * Offset (in line units) at which the delay saturates.
		 *
		 * @default 4.0
		 * @minimum 1
		 */
		::music_lyric_player::utils::config::Property<double> range = 4.0;
		/**
		 * Delay increment per offset unit, in `ms`.
		 *
		 * @default 50.0
		 * @minimum 1
		 */
		::music_lyric_player::utils::config::Property<double> step = 50.0;

		bool operator==(const StaggerConfig&) const = default;

		friend void overlay(StaggerConfig& dst, const StaggerConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.duration.assigned()) dst.duration = src.duration.value();
			if (src.easing.assigned()) dst.easing = src.easing.value();
			if (src.range.assigned()) dst.range = src.range.value();
			if (src.step.assigned()) dst.step = src.step.value();
		}

		friend void capture(StaggerConfig& delta, const StaggerConfig& prev, const StaggerConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.duration == next.duration)) delta.duration = next.duration.value();
			if (!(prev.easing == next.easing)) delta.easing = next.easing.value();
			if (!(prev.range == next.range)) delta.range = next.range.value();
			if (!(prev.step == next.step)) delta.step = next.step.value();
		}
	};

	/**
	 * Transition animation used when the active line changes.
	 */
	struct AnimationConfig {
		/**
		 * Cascade mode distributing per-line transition delays.
		 *
		 * - `Smooth` — all lines move together, no cascade
		 * - `Ripple` — symmetric cascade outward from the active line
		 * - `Directional` — nonlinear cascade following the latest active-line movement direction
		 * - `Stagger` — linear cascade following the latest active-line movement direction
		 *
		 * @default Mode::Smooth
		 */
		::music_lyric_player::utils::config::Property<Mode> mode = Mode::Smooth;
		/**
		 * Smooth mode parameters.
		 */
		SmoothConfig smooth;
		/**
		 * Ripple mode parameters.
		 */
		RippleConfig ripple;
		/**
		 * Directional mode parameters.
		 */
		DirectionalConfig directional;
		/**
		 * Stagger mode parameters.
		 */
		StaggerConfig stagger;

		bool operator==(const AnimationConfig&) const = default;

		friend void overlay(AnimationConfig& dst, const AnimationConfig& src, ::music_lyric_player::utils::config::Access key) {
			if (src.mode.assigned()) dst.mode = src.mode.value();
			overlay(dst.smooth, src.smooth, key);
			overlay(dst.ripple, src.ripple, key);
			overlay(dst.directional, src.directional, key);
			overlay(dst.stagger, src.stagger, key);
		}

		friend void capture(AnimationConfig& delta, const AnimationConfig& prev, const AnimationConfig& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.mode == next.mode)) delta.mode = next.mode.value();
			capture(delta.smooth, prev.smooth, next.smooth, key);
			capture(delta.ripple, prev.ripple, next.ripple, key);
			capture(delta.directional, prev.directional, next.directional, key);
			capture(delta.stagger, prev.stagger, next.stagger, key);
		}
	};

	/**
	 * Viewport scrolling that follows the active line.
	 */
	struct Root {
		/**
		 * Vertical anchor of the active line inside the viewport, as a ratio of its height.
		 *
		 * - `0.5` — keep the active line at the vertical center
		 * - `0.3` — keep the active line closer to the top
		 *
		 * @default 0.5
		 * @minimum 0
		 * @maximum 1
		 */
		::music_lyric_player::utils::config::Property<double> anchor = 0.5;
		/**
		 * Transition animation used when the active line changes.
		 */
		AnimationConfig animation;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			if (src.anchor.assigned()) dst.anchor = src.anchor.value();
			overlay(dst.animation, src.animation, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.anchor == next.anchor)) delta.anchor = next.anchor.value();
			capture(delta.animation, prev.animation, next.animation, key);
		}
	};

} // namespace music_lyric_player::rendering::config::scroll

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_SCROLL_CONFIG_GEN_H_
