// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_INTERLUDE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_INTERLUDE_CONFIG_GEN_H_

#include <string>

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::line::interlude {
	/**
	 * Visual style for one playback state of an interlude indicator.
	 */
	struct StyleConfig {
		/**
		 * Dot color for this playback state.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#ffffff"
		 * @example "#fff"
		 * @example "rgba(255, 255, 255, 0.8)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> color = "#ffffff";
		/**
		 * Dot opacity for this playback state.
		 *
		 * @default 1.0
		 * @minimum 0
		 * @maximum 1
		 */
		::music_lyric_player::utils::config::Property<double> opacity = 1.0;

		bool operator==(const StyleConfig&) const = default;

		friend void overlay(StyleConfig& dst, const StyleConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.color.assigned()) dst.color = src.color.value();
			if (src.opacity.assigned()) dst.opacity = src.opacity.value();
		}

		friend void capture(StyleConfig& delta, const StyleConfig& prev, const StyleConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.color == next.color)) delta.color = next.color.value();
			if (!(prev.opacity == next.opacity)) delta.opacity = next.opacity.value();
		}
	};

	/**
	 * Inactive and active styles of an interlude indicator.
	 */
	struct StateConfig {
		/**
		 * Style before and after the interlude is active.
		 */
		StyleConfig normal = StyleConfig{ .color = "#ffffff", .opacity = 0.2 };
		/**
		 * Style progressively filled while the interlude is active.
		 */
		StyleConfig active = StyleConfig{ .color = "#ffffff", .opacity = 0.8 };

		bool operator==(const StateConfig&) const = default;

		friend void overlay(StateConfig& dst, const StateConfig& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.normal, src.normal, key);
			overlay(dst.active, src.active, key);
		}

		friend void capture(StateConfig& delta, const StateConfig& prev, const StateConfig& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.normal, prev.normal, next.normal, key);
			capture(delta.active, prev.active, next.active, key);
		}
	};

	/**
	 * Geometry and state styles of instrumental-gap indicators.
	 */
	struct Root {
		/**
		 * Diameter of each indicator dot.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "16px"
		 * @example 16
		 * @example "16px"
		 */
		::music_lyric_player::utils::config::Property<::std::string> size = "16px";
		/**
		 * Inactive and active dot styles.
		 */
		StateConfig style;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			if (src.size.assigned()) dst.size = src.size.value();
			overlay(dst.style, src.style, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.size == next.size)) delta.size = next.size.value();
			capture(delta.style, prev.style, next.style, key);
		}
	};

} // namespace music_lyric_player::rendering::config::line::interlude

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_INTERLUDE_CONFIG_GEN_H_
