// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_INTERLUDE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_INTERLUDE_CONFIG_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_player::rendering::config::line::interlude {
	/**
	 * Visual style for one playback state of an interlude indicator.
	 */
	struct StyleConfig {
		/**
		 * Dot color for this playback state.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#ffffff"
		 * @example "#fff"
		 * @example "rgba(255, 255, 255, 0.8)"
		 */
		::std::string color = "#ffffff";
		/**
		 * Dot opacity for this playback state.
		 *
		 * @default 1.0
		 * @minimum 0
		 * @maximum 1
		 */
		double opacity = 1.0;
	};

	/**
	 * Inactive and active styles of an interlude indicator.
	 */
	struct StateConfig {
		/**
		 * Style before and after the interlude is active.
		 */
		StyleConfig normal = StyleConfig{ .color = "#ffffff", .opacity = 0.2 };
		/**
		 * Style progressively filled while the interlude is active.
		 */
		StyleConfig active = StyleConfig{ .color = "#ffffff", .opacity = 0.8 };
	};

	/**
	 * Geometry and state styles of instrumental-gap indicators.
	 */
	struct Root {
		/**
		 * Diameter of each indicator dot.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "16px"
		 * @example 16
		 * @example "16px"
		 */
		::std::string size = "16px";
		/**
		 * Inactive and active dot styles.
		 */
		StateConfig style;
	};

	struct StyleConfigPatch {
		::std::optional<::std::string> color;
		::std::optional<double> opacity;
	};

	struct StateConfigPatch {
		StyleConfigPatch normal;
		StyleConfigPatch active;
	};

	struct RootPatch {
		::std::optional<::std::string> size;
		StateConfigPatch style;
	};

	struct StyleConfigChange {
		bool color = false;
		bool opacity = false;
		bool any = false;
	};

	struct StateConfigChange {
		StyleConfigChange normal;
		StyleConfigChange active;
		bool any = false;
	};

	struct RootChange {
		bool size = false;
		StateConfigChange style;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(StyleConfig& cfg, const StyleConfigPatch& patch) {
		if (patch.color.has_value()) {
			cfg.color = *patch.color;
		}
		if (patch.opacity.has_value()) {
			cfg.opacity = *patch.opacity;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(StateConfig& cfg, const StateConfigPatch& patch) {
		apply(cfg.normal, patch.normal);
		apply(cfg.active, patch.active);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.size.has_value()) {
			cfg.size = *patch.size;
		}
		apply(cfg.style, patch.style);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline StyleConfigChange diff(const StyleConfig& prev, const StyleConfig& next) {
		StyleConfigChange change;
		change.color = prev.color != next.color;
		change.opacity = prev.opacity != next.opacity;
		change.any = change.color || change.opacity;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline StateConfigChange diff(const StateConfig& prev, const StateConfig& next) {
		StateConfigChange change;
		change.normal = diff(prev.normal, next.normal);
		change.active = diff(prev.active, next.active);
		change.any = change.normal.any || change.active.any;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.size = prev.size != next.size;
		change.style = diff(prev.style, next.style);
		change.any = change.size || change.style.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::line::interlude

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_INTERLUDE_CONFIG_GEN_H_
