// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONTAINER_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONTAINER_CONFIG_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_player::rendering::config::container {
	/**
	 * Soft fade at the top and bottom edges of the player.
	 *
	 * Lines ease out as they approach the viewport edge.
	 */
	struct FadeConfig {
		/**
		 * Whether to enable the edge fade.
		 *
		 * @default true
		 */
		bool enabled = true;
		/**
		 * Top fade range.
		 * A `%` value is relative to the viewport height.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "5%"
		 * @example "5%"
		 * @example "24px"
		 */
		::std::string top = "5%";
		/**
		 * Bottom fade range.
		 * A `%` value is relative to the viewport height.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "10%"
		 * @example "10%"
		 * @example "48px"
		 */
		::std::string bottom = "10%";
	};

	/**
	 * Background fill and padding of the player.
	 */
	struct Root {
		/**
		 * Background fill of the whole player.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#101014"
		 * @example "#101014"
		 * @example "rgb(16, 16, 20)"
		 */
		::std::string backgroundColor = "#101014";
		/**
		 * Horizontal padding on each side of the content.
		 * A `%` value is relative to the viewport width.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "48px"
		 * @example 48
		 * @example "48px"
		 * @example "5%"
		 */
		::std::string paddingX = "48px";
		/**
		 * Edge fade applied at the top and bottom of the player.
		 */
		FadeConfig fade;
	};

	struct FadeConfigPatch {
		::std::optional<bool> enabled;
		::std::optional<::std::string> top;
		::std::optional<::std::string> bottom;
	};

	struct RootPatch {
		::std::optional<::std::string> backgroundColor;
		::std::optional<::std::string> paddingX;
		FadeConfigPatch fade;
	};

	struct FadeConfigChange {
		bool enabled = false;
		bool top = false;
		bool bottom = false;
		bool any = false;
	};

	struct RootChange {
		bool backgroundColor = false;
		bool paddingX = false;
		FadeConfigChange fade;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(FadeConfig& cfg, const FadeConfigPatch& patch) {
		if (patch.enabled.has_value()) {
			cfg.enabled = *patch.enabled;
		}
		if (patch.top.has_value()) {
			cfg.top = *patch.top;
		}
		if (patch.bottom.has_value()) {
			cfg.bottom = *patch.bottom;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.backgroundColor.has_value()) {
			cfg.backgroundColor = *patch.backgroundColor;
		}
		if (patch.paddingX.has_value()) {
			cfg.paddingX = *patch.paddingX;
		}
		apply(cfg.fade, patch.fade);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline FadeConfigChange diff(const FadeConfig& prev, const FadeConfig& next) {
		FadeConfigChange change;
		change.enabled = prev.enabled != next.enabled;
		change.top = prev.top != next.top;
		change.bottom = prev.bottom != next.bottom;
		change.any = change.enabled || change.top || change.bottom;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.backgroundColor = prev.backgroundColor != next.backgroundColor;
		change.paddingX = prev.paddingX != next.paddingX;
		change.fade = diff(prev.fade, next.fade);
		change.any = change.backgroundColor || change.paddingX || change.fade.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::container

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONTAINER_CONFIG_GEN_H_
