// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONTAINER_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONTAINER_CONFIG_GEN_H_

#include <string>

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::container {
	/**
	 * Soft fade at the top and bottom edges of the player.
	 *
	 * Lines ease out as they approach the viewport edge.
	 */
	struct FadeConfig {
		/**
		 * Whether to enable the edge fade.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> enabled = true;
		/**
		 * Top fade range.
		 * A `%` value is relative to the viewport height.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "5%"
		 * @example "5%"
		 * @example "24px"
		 */
		::music_lyric_player::utils::config::Property<::std::string> top = "5%";
		/**
		 * Bottom fade range.
		 * A `%` value is relative to the viewport height.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "10%"
		 * @example "10%"
		 * @example "48px"
		 */
		::music_lyric_player::utils::config::Property<::std::string> bottom = "10%";

		bool operator==(const FadeConfig&) const = default;

		friend void overlay(FadeConfig& dst, const FadeConfig& src, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (src.enabled.assigned()) dst.enabled = src.enabled.value();
			if (src.top.assigned()) dst.top = src.top.value();
			if (src.bottom.assigned()) dst.bottom = src.bottom.value();
		}

		friend void capture(FadeConfig& delta, const FadeConfig& prev, const FadeConfig& next, [[maybe_unused]] ::music_lyric_player::utils::config::Access key) {
			if (!(prev.enabled == next.enabled)) delta.enabled = next.enabled.value();
			if (!(prev.top == next.top)) delta.top = next.top.value();
			if (!(prev.bottom == next.bottom)) delta.bottom = next.bottom.value();
		}
	};

	/**
	 * Background fill and padding of the player.
	 */
	struct Root {
		/**
		 * Background fill of the whole player.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#101014"
		 * @example "#101014"
		 * @example "rgb(16, 16, 20)"
		 */
		::music_lyric_player::utils::config::Property<::std::string> backgroundColor = "#101014";
		/**
		 * Horizontal padding on each side of the content.
		 * A `%` value is relative to the viewport width.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "48px"
		 * @example 48
		 * @example "48px"
		 * @example "5%"
		 */
		::music_lyric_player::utils::config::Property<::std::string> paddingX = "48px";
		/**
		 * Edge fade applied at the top and bottom of the player.
		 */
		FadeConfig fade;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			if (src.backgroundColor.assigned()) dst.backgroundColor = src.backgroundColor.value();
			if (src.paddingX.assigned()) dst.paddingX = src.paddingX.value();
			overlay(dst.fade, src.fade, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.backgroundColor == next.backgroundColor)) delta.backgroundColor = next.backgroundColor.value();
			if (!(prev.paddingX == next.paddingX)) delta.paddingX = next.paddingX.value();
			capture(delta.fade, prev.fade, next.fade, key);
		}
	};

} // namespace music_lyric_player::rendering::config::container

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_CONTAINER_CONFIG_GEN_H_
