// clang-format off
// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LAYOUT_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LAYOUT_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"

namespace music_lyric_player::render::config::layout {
	/**
	 * Geometric layout rules applied to every lyric line.
	 */
	struct Root {
		/**
		 * Horizontal alignment of lines within the container.
		 *
		 * - `0` — left
		 * - `1` — center
		 * - `2` — right
		 *
		 * @default 0
		 */
		int align = 0;
		/**
		 * Vertical spacing between adjacent lines.
		 * A bare number or `px` is absolute; `%` is relative to the viewport height.
		 *
		 * @default "16px"
		 * @example 16
		 * @example "16px"
		 * @example "2%"
		 */
		::std::string gap = "16px";
	};

	struct RootPatch {
		::std::optional<int> align;
		::std::optional<::std::string> gap;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Root& cfg, const RootPatch& patch) {
		if (patch.align.has_value()) {
			cfg.align = *patch.align;
		}
		if (patch.gap.has_value()) {
			cfg.gap = *patch.gap;
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Root& prev, const Root& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.align != next.align) {
			keys.insert(prefix + "align");
		}
		if (prev.gap != next.gap) {
			keys.insert(prefix + "gap");
		}
	}

	namespace RootKeys {
		inline constexpr ::std::string_view align{"align"};
		inline constexpr ::std::string_view gap{"gap"};
	} // namespace RootKeys

} // namespace music_lyric_player::render::config::layout

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LAYOUT_CONFIG_GEN_H_
// clang-format on
