// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_SCROLL_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_SCROLL_CONFIG_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_player::render::config::scroll {
	/**
	 * Scroll cascade mode selecting how per-line transition delays are distributed.
	 */
	enum class Mode {
		Smooth,
		Ripple,
		Directional,
		Stagger,
	};

	/**
	 * Parameters for the Smooth mode: a uniform, non-cascade transition.
	 */
	struct SmoothConfig {
		/**
		 * Fixed delay before the transition starts, in `ms`.
		 *
		 * @default 0.0
		 */
		double delay = 0.0;
	};

	/**
	 * Parameters for the Ripple mode: a symmetric cascade radiating outward from the active line.
	 */
	struct RippleConfig {
		/**
		 * Offset (in line units) at which the per-line delay saturates.
		 * Lines with `|offset| >= range` all receive the maximum delay.
		 *
		 * @default 5.0
		 * @minimum 1
		 */
		double range = 5.0;
		/**
		 * Delay increment per offset unit, in `ms`; scales the cascade curve.
		 *
		 * @default 40.0
		 * @minimum 10
		 */
		double step = 40.0;
	};

	/**
	 * Parameters for the Directional mode: played lines move first, upcoming lines follow.
	 */
	struct DirectionalConfig {
		/**
		 * Offset (in line units) at which the per-line delay saturates.
		 *
		 * @default 5.0
		 * @minimum 1
		 */
		double range = 5.0;
		/**
		 * Delay increment per offset unit, in `ms`.
		 *
		 * @default 40.0
		 * @minimum 10
		 */
		double step = 40.0;
	};

	/**
	 * Parameters for the Stagger mode: a linear, direction-sensitive stagger cascade (legacy).
	 */
	struct StaggerConfig {
		/**
		 * Offset (in line units) at which the delay saturates.
		 *
		 * @default 4.0
		 * @minimum 1
		 */
		double range = 4.0;
		/**
		 * Delay increment per offset unit, in `ms`.
		 *
		 * @default 50.0
		 * @minimum 1
		 */
		double step = 50.0;
	};

	/**
	 * Transition animation used when the active line changes.
	 */
	struct AnimationConfig {
		/**
		 * Cascade mode distributing per-line transition delays.
		 *
		 * - `Smooth` — all lines move together, no cascade
		 * - `Ripple` — symmetric cascade outward from the active line
		 * - `Directional` — played lines move first, upcoming lines follow
		 * - `Stagger` — legacy linear stagger; delay saturates at `range`
		 *
		 * @default Mode::Smooth
		 */
		Mode mode = Mode::Smooth;
		/**
		 * Transition duration of each individual line, in `ms`.
		 * In cascade modes the total visual length is roughly `duration + maxDelay`.
		 * `0` snaps to the target without easing.
		 *
		 * @default 500.0
		 */
		double duration = 500.0;
		/**
		 * Easing curve for the transition.
		 * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
		 *
		 * @default "ease"
		 * @example "ease-in-out"
		 * @example "cubic-bezier(0.4, 0, 0.2, 1)"
		 */
		::std::string easing = "ease";
		/**
		 * Smooth mode parameters.
		 */
		SmoothConfig smooth;
		/**
		 * Ripple mode parameters.
		 */
		RippleConfig ripple;
		/**
		 * Directional mode parameters.
		 */
		DirectionalConfig directional;
		/**
		 * Stagger mode parameters.
		 */
		StaggerConfig stagger;
	};

	/**
	 * Viewport scrolling that follows the active line.
	 */
	struct Root {
		/**
		 * Vertical anchor of the active line inside the viewport, as a ratio of its height.
		 *
		 * - `0.5` — keep the active line at the vertical center
		 * - `0.3` — keep the active line closer to the top
		 *
		 * @default 0.5
		 * @minimum 0
		 * @maximum 1
		 */
		double anchor = 0.5;
		/**
		 * Transition animation used when the active line changes.
		 */
		AnimationConfig animation;
	};

	struct SmoothConfigPatch {
		::std::optional<double> delay;
	};

	struct RippleConfigPatch {
		::std::optional<double> range;
		::std::optional<double> step;
	};

	struct DirectionalConfigPatch {
		::std::optional<double> range;
		::std::optional<double> step;
	};

	struct StaggerConfigPatch {
		::std::optional<double> range;
		::std::optional<double> step;
	};

	struct AnimationConfigPatch {
		::std::optional<Mode> mode;
		::std::optional<double> duration;
		::std::optional<::std::string> easing;
		SmoothConfigPatch smooth;
		RippleConfigPatch ripple;
		DirectionalConfigPatch directional;
		StaggerConfigPatch stagger;
	};

	struct RootPatch {
		::std::optional<double> anchor;
		AnimationConfigPatch animation;
	};

	struct SmoothConfigChange {
		bool delay = false;
		bool any = false;
	};

	struct RippleConfigChange {
		bool range = false;
		bool step = false;
		bool any = false;
	};

	struct DirectionalConfigChange {
		bool range = false;
		bool step = false;
		bool any = false;
	};

	struct StaggerConfigChange {
		bool range = false;
		bool step = false;
		bool any = false;
	};

	struct AnimationConfigChange {
		bool mode = false;
		bool duration = false;
		bool easing = false;
		SmoothConfigChange smooth;
		RippleConfigChange ripple;
		DirectionalConfigChange directional;
		StaggerConfigChange stagger;
		bool any = false;
	};

	struct RootChange {
		bool anchor = false;
		AnimationConfigChange animation;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(SmoothConfig& cfg, const SmoothConfigPatch& patch) {
		if (patch.delay.has_value()) {
			cfg.delay = *patch.delay;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(RippleConfig& cfg, const RippleConfigPatch& patch) {
		if (patch.range.has_value()) {
			cfg.range = *patch.range;
		}
		if (patch.step.has_value()) {
			cfg.step = *patch.step;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(DirectionalConfig& cfg, const DirectionalConfigPatch& patch) {
		if (patch.range.has_value()) {
			cfg.range = *patch.range;
		}
		if (patch.step.has_value()) {
			cfg.step = *patch.step;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(StaggerConfig& cfg, const StaggerConfigPatch& patch) {
		if (patch.range.has_value()) {
			cfg.range = *patch.range;
		}
		if (patch.step.has_value()) {
			cfg.step = *patch.step;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(AnimationConfig& cfg, const AnimationConfigPatch& patch) {
		if (patch.mode.has_value()) {
			cfg.mode = *patch.mode;
		}
		if (patch.duration.has_value()) {
			cfg.duration = *patch.duration;
		}
		if (patch.easing.has_value()) {
			cfg.easing = *patch.easing;
		}
		apply(cfg.smooth, patch.smooth);
		apply(cfg.ripple, patch.ripple);
		apply(cfg.directional, patch.directional);
		apply(cfg.stagger, patch.stagger);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.anchor.has_value()) {
			cfg.anchor = *patch.anchor;
		}
		apply(cfg.animation, patch.animation);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline SmoothConfigChange diff(const SmoothConfig& prev, const SmoothConfig& next) {
		SmoothConfigChange change;
		change.delay = prev.delay != next.delay;
		change.any = change.delay;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RippleConfigChange diff(const RippleConfig& prev, const RippleConfig& next) {
		RippleConfigChange change;
		change.range = prev.range != next.range;
		change.step = prev.step != next.step;
		change.any = change.range || change.step;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline DirectionalConfigChange diff(const DirectionalConfig& prev, const DirectionalConfig& next) {
		DirectionalConfigChange change;
		change.range = prev.range != next.range;
		change.step = prev.step != next.step;
		change.any = change.range || change.step;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline StaggerConfigChange diff(const StaggerConfig& prev, const StaggerConfig& next) {
		StaggerConfigChange change;
		change.range = prev.range != next.range;
		change.step = prev.step != next.step;
		change.any = change.range || change.step;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline AnimationConfigChange diff(const AnimationConfig& prev, const AnimationConfig& next) {
		AnimationConfigChange change;
		change.mode = prev.mode != next.mode;
		change.duration = prev.duration != next.duration;
		change.easing = prev.easing != next.easing;
		change.smooth = diff(prev.smooth, next.smooth);
		change.ripple = diff(prev.ripple, next.ripple);
		change.directional = diff(prev.directional, next.directional);
		change.stagger = diff(prev.stagger, next.stagger);
		change.any = change.mode || change.duration || change.easing || change.smooth.any || change.ripple.any || change.directional.any || change.stagger.any;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.anchor = prev.anchor != next.anchor;
		change.animation = diff(prev.animation, next.animation);
		change.any = change.anchor || change.animation.any;
		return change;
	}

} // namespace music_lyric_player::render::config::scroll

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_SCROLL_CONFIG_GEN_H_
