// Generated by generate-config script from config.schema.json. DO NOT EDIT.

package music.lyric.player.skia.config

import org.json.JSONObject

/**
 * Timing-engine configuration.
 */
data class PlaybackConfig(
    /**
     * Whether gaps in the active-line indices are filled so the active range stays contiguous.
     *
     * @default true
     */
    val bridgeActive: Boolean? = null,
    /**
     * Window in milliseconds within which consecutive lines cluster and deactivate together.
     *
     * @default 300.0
     */
    val mergeWindow: Double? = null,
    /**
     * Maximum number of lines in one merge batch; a value of 0 or less leaves it unbounded.
     *
     * @default 3
     */
    val mergeLimit: Int? = null,
    /**
     * Global layer of the three-layer lyric offset.
     */
    val offset: OffsetConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.bridgeActive?.let { json.put("bridgeActive", it) }
        this.mergeWindow?.let { json.put("mergeWindow", it) }
        this.mergeLimit?.let { json.put("mergeLimit", it) }
        this.offset?.let { json.put("offset", it.toJson()) }
        return json
    }
}

/**
 * The global layer of the three-layer offset (global + meta + temp).
 */
data class OffsetConfig(
    /**
     * Offset in milliseconds applied to every song.
     *
     * @default 0.0
     */
    val global: Double? = null,
    /**
     * Whether the lyric's own meta offset is applied on top of the global one.
     *
     * @default true
     */
    val useMeta: Boolean? = null,
    /**
     * Whether the temporary offset is cleared when a new lyric loads.
     *
     * @default true
     */
    val resetTempOnLyricChange: Boolean? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.global?.let { json.put("global", it) }
        this.useMeta?.let { json.put("useMeta", it) }
        this.resetTempOnLyricChange?.let { json.put("resetTempOnLyricChange", it) }
        return json
    }
}
