// Generated by generate-config script from config.schema.json. DO NOT EDIT.

package music.lyric.player.skia.config

import org.json.JSONObject

enum class LayoutAlign(val wire: String) {
    Left("Left"),
    Center("Center"),
    Right("Right"),
}

enum class ScrollMode(val wire: String) {
    Smooth("Smooth"),
    Ripple("Ripple"),
    Directional("Directional"),
    Stagger("Stagger"),
}

enum class LineNormalMainUse(val wire: String) {
    Plain("Plain"),
    Syllable("Syllable"),
}

/**
 * Renderer configuration.
 */
data class RenderingConfig(
    /**
     * Background fill and padding of the player.
     */
    val container: ContainerConfig? = null,
    /**
     * Alignment and spacing between lyric lines.
     */
    val layout: LayoutConfig? = null,
    /**
     * Viewport scrolling and its transition animation.
     */
    val scroll: ScrollConfig? = null,
    /**
     * Font and per-state colors of lyric lines.
     */
    val line: LineConfig? = null,
    /**
     * Distance-from-focus scale and blur effects.
     */
    val effect: EffectConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.container?.let { json.put("container", it.toJson()) }
        this.layout?.let { json.put("layout", it.toJson()) }
        this.scroll?.let { json.put("scroll", it.toJson()) }
        this.line?.let { json.put("line", it.toJson()) }
        this.effect?.let { json.put("effect", it.toJson()) }
        return json
    }
}

/**
 * Background fill and padding of the player.
 */
data class ContainerConfig(
    /**
     * Background fill of the whole player.
     * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
     *
     * @default "#101014"
     * @example "#101014"
     * @example "rgb(16, 16, 20)"
     */
    val backgroundColor: String? = null,
    /**
     * Horizontal padding on each side of the content.
     * A `%` value is relative to the viewport width.
     * A bare number or `px` is an absolute length in logical pixels.
     *
     * @default "48px"
     * @example 48
     * @example "48px"
     * @example "5%"
     */
    val paddingX: String? = null,
    /**
     * Edge fade applied at the top and bottom of the player.
     */
    val fade: ContainerFadeConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.backgroundColor?.let { json.put("backgroundColor", it) }
        this.paddingX?.let { json.put("paddingX", it) }
        this.fade?.let { json.put("fade", it.toJson()) }
        return json
    }
}

/**
 * Soft fade at the top and bottom edges of the player.
 *
 * Lines ease out as they approach the viewport edge.
 */
data class ContainerFadeConfig(
    /**
     * Whether to enable the edge fade.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Top fade range.
     * A `%` value is relative to the viewport height.
     * A bare number or `px` is an absolute length in logical pixels.
     *
     * @default "5%"
     * @example "5%"
     * @example "24px"
     */
    val top: String? = null,
    /**
     * Bottom fade range.
     * A `%` value is relative to the viewport height.
     * A bare number or `px` is an absolute length in logical pixels.
     *
     * @default "10%"
     * @example "10%"
     * @example "48px"
     */
    val bottom: String? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.top?.let { json.put("top", it) }
        this.bottom?.let { json.put("bottom", it) }
        return json
    }
}

/**
 * Alignment and spacing applied to every lyric line.
 */
data class LayoutConfig(
    /**
     * Horizontal alignment of lines within the container.
     *
     * @default "Left"
     */
    val align: LayoutAlign? = null,
    /**
     * Vertical spacing between adjacent lines.
     * A `%` value is relative to the viewport height.
     * A bare number or `px` is an absolute length in logical pixels.
     *
     * @default "16px"
     * @example 16
     * @example "16px"
     * @example "2%"
     */
    val gap: String? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.align?.let { json.put("align", it.wire) }
        this.gap?.let { json.put("gap", it) }
        return json
    }
}

/**
 * Viewport scrolling that follows the active line.
 */
data class ScrollConfig(
    /**
     * Vertical anchor of the active line inside the viewport, as a ratio of its height.
     *
     * - `0.5`: keep the active line at the vertical center
     * - `0.3`: keep the active line closer to the top
     *
     * @default 0.5
     * @minimum 0
     * @maximum 1
     */
    val anchor: Double? = null,
    /**
     * Transition animation used when the active line changes.
     */
    val animation: ScrollAnimationConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.anchor?.let { json.put("anchor", it) }
        this.animation?.let { json.put("animation", it.toJson()) }
        return json
    }
}

/**
 * Transition animation used when the active line changes.
 */
data class ScrollAnimationConfig(
    /**
     * Cascade mode distributing per-line transition delays.
     *
     * - `Smooth`: all lines move together, no cascade
     * - `Ripple`: symmetric cascade outward from the active line
     * - `Directional`: nonlinear cascade following the latest active-line movement direction
     * - `Stagger`: linear cascade following the latest active-line movement direction
     *
     * @default "Smooth"
     */
    val mode: ScrollMode? = null,
    /**
     * Smooth mode parameters.
     */
    val smooth: ScrollSmoothConfig? = null,
    /**
     * Ripple mode parameters.
     */
    val ripple: ScrollRippleConfig? = null,
    /**
     * Directional mode parameters.
     */
    val directional: ScrollDirectionalConfig? = null,
    /**
     * Stagger mode parameters.
     */
    val stagger: ScrollStaggerConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.mode?.let { json.put("mode", it.wire) }
        this.smooth?.let { json.put("smooth", it.toJson()) }
        this.ripple?.let { json.put("ripple", it.toJson()) }
        this.directional?.let { json.put("directional", it.toJson()) }
        this.stagger?.let { json.put("stagger", it.toJson()) }
        return json
    }
}

/**
 * Parameters for the Smooth mode: a uniform, non-cascade transition.
 */
data class ScrollSmoothConfig(
    /**
     * Transition duration of each individual line, in `ms`.
     * In cascade modes the total visual length is roughly `duration + maxDelay`.
     * `0` snaps to the target without easing.
     *
     * @default 500.0
     */
    val duration: Double? = null,
    /**
     * Easing curve for the transition.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "ease"
     * @example "ease-in-out"
     * @example "cubic-bezier(0.4, 0, 0.2, 1)"
     */
    val easing: String? = null,
    /**
     * Fixed delay before the transition starts, in `ms`.
     *
     * @default 0.0
     */
    val delay: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.duration?.let { json.put("duration", it) }
        this.easing?.let { json.put("easing", it) }
        this.delay?.let { json.put("delay", it) }
        return json
    }
}

/**
 * Parameters for the Ripple mode: a symmetric cascade radiating outward from the active line.
 */
data class ScrollRippleConfig(
    /**
     * Transition duration of each individual line, in `ms`.
     * In cascade modes the total visual length is roughly `duration + maxDelay`.
     * `0` snaps to the target without easing.
     *
     * @default 500.0
     */
    val duration: Double? = null,
    /**
     * Easing curve for the transition.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "ease"
     * @example "ease-in-out"
     * @example "cubic-bezier(0.4, 0, 0.2, 1)"
     */
    val easing: String? = null,
    /**
     * Offset (in line units) at which the per-line delay saturates.
     * Lines with `|offset| >= range` all receive the maximum delay.
     *
     * @default 5.0
     * @minimum 1
     */
    val range: Double? = null,
    /**
     * Delay increment per offset unit, in `ms`; scales the cascade curve.
     *
     * @default 40.0
     * @minimum 10
     */
    val step: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.duration?.let { json.put("duration", it) }
        this.easing?.let { json.put("easing", it) }
        this.range?.let { json.put("range", it) }
        this.step?.let { json.put("step", it) }
        return json
    }
}

/**
 * Parameters for the Directional mode: a nonlinear cascade following the latest active-line movement direction.
 */
data class ScrollDirectionalConfig(
    /**
     * Transition duration of each individual line, in `ms`.
     * In cascade modes the total visual length is roughly `duration + maxDelay`.
     * `0` snaps to the target without easing.
     *
     * @default 500.0
     */
    val duration: Double? = null,
    /**
     * Easing curve for the transition.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "ease"
     * @example "ease-in-out"
     * @example "cubic-bezier(0.4, 0, 0.2, 1)"
     */
    val easing: String? = null,
    /**
     * Offset (in line units) at which the per-line delay saturates.
     *
     * @default 5.0
     * @minimum 1
     */
    val range: Double? = null,
    /**
     * Delay increment per offset unit, in `ms`.
     *
     * @default 40.0
     * @minimum 10
     */
    val step: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.duration?.let { json.put("duration", it) }
        this.easing?.let { json.put("easing", it) }
        this.range?.let { json.put("range", it) }
        this.step?.let { json.put("step", it) }
        return json
    }
}

/**
 * Parameters for the Stagger mode: a linear cascade following the latest active-line movement direction.
 */
data class ScrollStaggerConfig(
    /**
     * Transition duration of each individual line, in `ms`.
     * In cascade modes the total visual length is roughly `duration + maxDelay`.
     * `0` snaps to the target without easing.
     *
     * @default 500.0
     */
    val duration: Double? = null,
    /**
     * Easing curve for the transition.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "ease"
     * @example "ease-in-out"
     * @example "cubic-bezier(0.4, 0, 0.2, 1)"
     */
    val easing: String? = null,
    /**
     * Offset (in line units) at which the delay saturates.
     *
     * @default 4.0
     * @minimum 1
     */
    val range: Double? = null,
    /**
     * Delay increment per offset unit, in `ms`.
     *
     * @default 50.0
     * @minimum 1
     */
    val step: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.duration?.let { json.put("duration", it) }
        this.easing?.let { json.put("easing", it) }
        this.range?.let { json.put("range", it) }
        this.step?.let { json.put("step", it) }
        return json
    }
}

/**
 * Normal-line rendering and instrumental-gap indicators.
 */
data class LineConfig(
    /**
     * Rendering settings of vocal lyric lines.
     */
    val normal: LineNormalConfig? = null,
    /**
     * Instrumental-gap indicator geometry and animation styles.
     */
    val interlude: LineInterludeConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.normal?.let { json.put("normal", it.toJson()) }
        this.interlude?.let { json.put("interlude", it.toJson()) }
        return json
    }
}

/**
 * Rendering settings of vocal lyric lines.
 */
data class LineNormalConfig(
    /**
     * Appearance shared by the main vocal line and its annotation sub-lines.
     */
    val base: LineNormalBase? = null,
    /**
     * Rendering mode and settings of the main vocal content.
     */
    val main: LineNormalMainConfig? = null,
    /**
     * Translation and romanization sub-lines beneath the main content.
     */
    val annotation: LineNormalAnnotationConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.base?.let { json.put("base", it.toJson()) }
        this.main?.let { json.put("main", it.toJson()) }
        this.annotation?.let { json.put("annotation", it.toJson()) }
        return json
    }
}

/**
 * Appearance shared by the main vocal line and its annotation sub-lines.
 */
data class LineNormalBase(
    /**
     * Preferred BCP-47 tag shared by the line and inherited by its annotation rows when they set none; used to choose among coexisting translations or romanizations.
     *
     * @default "zh-hans"
     */
    val language: String? = null,
    /**
     * Font shared by every line.
     */
    val font: CommonFontConfig? = null,
    /**
     * Inactive and active styles shared by normal lyric lines.
     */
    val style: CommonStateStyleConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.language?.let { json.put("language", it) }
        this.font?.let { json.put("font", it.toJson()) }
        this.style?.let { json.put("style", it.toJson()) }
        return json
    }
}

/**
 * Font appearance shared by lyric lines and their annotation sub-lines.
 */
data class CommonFontConfig(
    /**
     * Font family name; empty uses the platform default.
     *
     * @example "PingFang SC"
     */
    val family: String? = null,
    /**
     * Font size of the lyric lines.
     * A `%` value is relative to the parent line's font size (e.g. translation / background lines).
     * A bare number or `px` is an absolute length in logical pixels.
     *
     * @default "34px"
     * @example 34
     * @example "34px"
     * @example "80%"
     */
    val size: String? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.family?.let { json.put("family", it) }
        this.size?.let { json.put("size", it) }
        return json
    }
}

/**
 * Inactive, active, and played styles shared by normal lyric lines and their annotation sub-lines.
 */
data class CommonStateStyleConfig(
    /**
     * Style of inactive lines.
     */
    val normal: CommonStyleConfig? = null,
    /**
     * Style of active lines.
     */
    val active: CommonStyleConfig? = null,
    /**
     * Style of played lines that have already been sung.
     */
    val played: CommonStyleConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.normal?.let { json.put("normal", it.toJson()) }
        this.active?.let { json.put("active", it.toJson()) }
        this.played?.let { json.put("played", it.toJson()) }
        return json
    }
}

/**
 * Visual style for a single render state.
 */
data class CommonStyleConfig(
    /**
     * Color of the render state.
     * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
     *
     * @default "#000000"
     * @example "#fff"
     * @example "rgba(255, 255, 255, 0.8)"
     */
    val color: String? = null,
    /**
     * Opacity of the render state in the [0, 1] range; 1 is fully opaque.
     *
     * @default 1.0
     * @minimum 0
     * @maximum 1
     */
    val opacity: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.color?.let { json.put("color", it) }
        this.opacity?.let { json.put("opacity", it) }
        return json
    }
}

/**
 * Rendering mode and settings of a normal line's main content.
 */
data class LineNormalMainConfig(
    /**
     * Preferred renderer; lyrics without word timing still fall back to plain text.
     *
     * @default "Syllable"
     */
    val use: LineNormalMainUse? = null,
    /**
     * Word-timed karaoke rendering settings.
     */
    val syllable: LineNormalMainSyllableConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.use?.let { json.put("use", it.wire) }
        this.syllable?.let { json.put("syllable", it.toJson()) }
        return json
    }
}

/**
 * Word-timed karaoke rendering settings.
 */
data class LineNormalMainSyllableConfig(
    /**
     * Font of the karaoke main content; inherits the base line font when unset.
     *
     * @see line.normal.base.font
     */
    val font: CommonFontConfig? = null,
    /**
     * Inactive, active, and played styles of the karaoke main content; inherit the base line styles when unset.
     *
     * @see line.normal.base.style
     */
    val style: CommonStateStyleConfig? = null,
    /**
     * Timed word rendering and animation settings.
     */
    val word: LineNormalMainSyllableWordConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.font?.let { json.put("font", it.toJson()) }
        this.style?.let { json.put("style", it.toJson()) }
        this.word?.let { json.put("word", it.toJson()) }
        return json
    }
}

/**
 * Rendering settings of each timed word.
 */
data class LineNormalMainSyllableWordConfig(
    /**
     * Float and reveal animations of the word.
     */
    val animation: LineNormalMainSyllableWordAnimationConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.animation?.let { json.put("animation", it.toJson()) }
        return json
    }
}

/**
 * Animation settings of timed words.
 */
data class LineNormalMainSyllableWordAnimationConfig(
    /**
     * Vertical word motion.
     */
    val floating: LineNormalMainSyllableFloatConfig? = null,
    /**
     * Karaoke color reveal mask.
     */
    val mask: LineNormalMainSyllableMaskConfig? = null,
    /**
     * Per-character emphasize effect of stressed words.
     */
    val emphasize: LineNormalMainSyllableEmphasizeConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.floating?.let { json.put("floating", it.toJson()) }
        this.mask?.let { json.put("mask", it.toJson()) }
        this.emphasize?.let { json.put("emphasize", it.toJson()) }
        return json
    }
}

/**
 * Vertical motion applied to each timed word.
 */
data class LineNormalMainSyllableFloatConfig(
    /**
     * Whether timed words float while they are sung.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Starting vertical offset in logical pixels.
     *
     * @default 0.0
     */
    val from: Double? = null,
    /**
     * Ending vertical offset in logical pixels.
     *
     * @default -2.0
     */
    val to: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.from?.let { json.put("from", it) }
        this.to?.let { json.put("to", it) }
        return json
    }
}

/**
 * Left-to-right karaoke reveal mask.
 */
data class LineNormalMainSyllableMaskConfig(
    /**
     * Whether active words reveal progressively instead of switching immediately.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Soft-edge sizing of the reveal boundary.
     */
    val feather: LineNormalMainSyllableMaskFeatherConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.feather?.let { json.put("feather", it.toJson()) }
        return json
    }
}

/**
 * Soft-edge sizing of the karaoke reveal mask.
 */
data class LineNormalMainSyllableMaskFeatherConfig(
    /**
     * Base feather width as a multiple of word height.
     *
     * @default 0.5
     * @minimum 0
     * @maximum 2
     */
    val normal: Double? = null,
    /**
     * Feather multiplier for the first word.
     *
     * @default 1.5
     * @minimum 0
     * @maximum 5
     */
    val first: Double? = null,
    /**
     * Feather multiplier for the last word.
     *
     * @default 0.5
     * @minimum 0
     * @maximum 5
     */
    val last: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.normal?.let { json.put("normal", it) }
        this.first?.let { json.put("first", it) }
        this.last?.let { json.put("last", it) }
        return json
    }
}

/**
 * Per-character emphasize effect of stressed syllables; at least one sub-effect must be enabled for the per-character split to happen.
 */
data class LineNormalMainSyllableEmphasizeConfig(
    /**
     * Master switch for the entire emphasize feature.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Sub-effects.
     */
    val effects: LineNormalMainSyllableEmphasizeEffectsConfig? = null,
    /**
     * Minimum animation duration in milliseconds; shorter syllables still emphasize but their timeline lasts at least this long.
     *
     * @default 1000.0
     * @minimum 0
     */
    val minDuration: Double? = null,
    /**
     * Playback rate used to wind down an in-flight per-character animation when the line leaves the active state.
     *
     * @default 4.0
     * @minimum 1
     */
    val disablePlaybackRate: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.effects?.let { json.put("effects", it.toJson()) }
        this.minDuration?.let { json.put("minDuration", it) }
        this.disablePlaybackRate?.let { json.put("disablePlaybackRate", it) }
        return json
    }
}

/**
 * Independently togglable sub-effects that compose the emphasize animation.
 */
data class LineNormalMainSyllableEmphasizeEffectsConfig(
    /**
     * Main per-character transform.
     */
    val main: LineNormalMainSyllableEmphasizeMainConfig? = null,
    /**
     * Glow halo.
     */
    val glow: LineNormalMainSyllableEmphasizeGlowConfig? = null,
    /**
     * Secondary float layer.
     */
    val floating: LineNormalMainSyllableEmphasizeFloatConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.main?.let { json.put("main", it.toJson()) }
        this.glow?.let { json.put("glow", it.toJson()) }
        this.floating?.let { json.put("floating", it.toJson()) }
        return json
    }
}

/**
 * Core per-character transform of the emphasize effect: a scale pulse with an outward fan-out and an upward lift.
 */
data class LineNormalMainSyllableEmphasizeMainConfig(
    /**
     * Whether the main transform animation runs.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Peak scale increment; the character's peak scale is `1 + scale * intensity`, where the intensity derives from the syllable's duration.
     *
     * @default 0.1
     * @minimum 0
     */
    val scale: Double? = null,
    /**
     * Peak outward horizontal shift per character in logical pixels; characters fan out from the word's center.
     *
     * @default 1.0
     * @minimum 0
     */
    val offsetHorizontal: Double? = null,
    /**
     * Peak upward vertical shift in logical pixels, applied uniformly to every character.
     *
     * @default 1.0
     * @minimum 0
     */
    val offsetVertical: Double? = null,
    /**
     * Easing applied from rest to the peak at the pulse midpoint.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "cubic-bezier(0.2, 0.4, 0.58, 1)"
     */
    val easingRise: String? = null,
    /**
     * Easing applied from the peak back to rest.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "cubic-bezier(0.3, 0, 0.58, 1)"
     */
    val easingFall: String? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.scale?.let { json.put("scale", it) }
        this.offsetHorizontal?.let { json.put("offsetHorizontal", it) }
        this.offsetVertical?.let { json.put("offsetVertical", it) }
        this.easingRise?.let { json.put("easingRise", it) }
        this.easingFall?.let { json.put("easingFall", it) }
        return json
    }
}

/**
 * Glow halo rendered behind emphasized characters; the only sub-effect that defaults to off because every character costs one blur per frame.
 */
data class LineNormalMainSyllableEmphasizeGlowConfig(
    /**
     * Whether to render the glow.
     *
     * @default false
     */
    val enabled: Boolean? = null,
    /**
     * Glow color; an unparseable string silently disables the glow, acting as a soft kill switch.
     * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
     *
     * @default "#000000"
     */
    val color: String? = null,
    /**
     * Easing applied from rest to the peak at the pulse midpoint.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "cubic-bezier(0.2, 0.4, 0.58, 1)"
     */
    val easingRise: String? = null,
    /**
     * Easing applied from the peak back to rest.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "cubic-bezier(0.3, 0, 0.58, 1)"
     */
    val easingFall: String? = null,
    /**
     * Maximum glow radius in logical pixels; the duration-derived intensity clamps it further so short syllables get a tighter halo.
     *
     * @default 9.0
     * @minimum 0
     */
    val maxRadius: Double? = null,
    /**
     * Peak glow alpha in the `[0, 1]` range.
     *
     * @default 1.0
     * @minimum 0
     * @maximum 1
     */
    val maxAlpha: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.color?.let { json.put("color", it) }
        this.easingRise?.let { json.put("easingRise", it) }
        this.easingFall?.let { json.put("easingFall", it) }
        this.maxRadius?.let { json.put("maxRadius", it) }
        this.maxAlpha?.let { json.put("maxAlpha", it) }
        return json
    }
}

/**
 * Secondary bounce layered on top of the per-word float animation.
 */
data class LineNormalMainSyllableEmphasizeFloatConfig(
    /**
     * Whether to enable the secondary float.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Float timing.
     */
    val duration: LineNormalMainSyllableEmphasizeFloatDurationConfig? = null,
    /**
     * Peak upward displacement in logical pixels.
     *
     * @default 2.0
     * @minimum 0
     */
    val amplitude: Double? = null,
    /**
     * Easing applied to each half of the bounce.
     * Accepts `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` or `cubic-bezier(x1, y1, x2, y2)`.
     *
     * @default "cubic-bezier(0.45, 0, 0.55, 1)"
     */
    val easing: String? = null,
    /**
     * Amplified float for background lines.
     */
    val background: LineNormalMainSyllableEmphasizeFloatBackgroundConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.duration?.let { json.put("duration", it.toJson()) }
        this.amplitude?.let { json.put("amplitude", it) }
        this.easing?.let { json.put("easing", it) }
        this.background?.let { json.put("background", it.toJson()) }
        return json
    }
}

/**
 * Timing controls of the secondary float layer.
 */
data class LineNormalMainSyllableEmphasizeFloatDurationConfig(
    /**
     * Float duration as a multiple of the main emphasize duration; values above 1 make the float linger after the main effect settles.
     *
     * @default 1.4
     * @minimum 0
     */
    val scale: Double? = null,
    /**
     * Milliseconds the float starts before the main emphasize effect.
     *
     * @default 400.0
     * @minimum 0
     */
    val lead: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.scale?.let { json.put("scale", it) }
        this.lead?.let { json.put("lead", it) }
        return json
    }
}

/**
 * Amplified float for background lines, layered on the emphasize float.
 */
data class LineNormalMainSyllableEmphasizeFloatBackgroundConfig(
    /**
     * Whether background lines get an amplified float.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Float amplitude multiplier applied on background lines.
     *
     * @default 2.0
     * @minimum 0
     */
    val scale: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.scale?.let { json.put("scale", it) }
        return json
    }
}

/**
 * Annotation sub-lines beneath the main vocal line.
 */
data class LineNormalAnnotationConfig(
    /**
     * Master switch; when false both rows hide regardless of their own visible.
     *
     * @default true
     */
    val visible: Boolean? = null,
    /**
     * Shared base inherited by all annotation rows.
     */
    val base: LineNormalAnnotationBase? = null,
    /**
     * Romanization row overrides.
     */
    val roman: LineNormalAnnotationRoman? = null,
    /**
     * Translation row overrides.
     */
    val translate: LineNormalAnnotationTranslate? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.visible?.let { json.put("visible", it) }
        this.base?.let { json.put("base", it.toJson()) }
        this.roman?.let { json.put("roman", it.toJson()) }
        this.translate?.let { json.put("translate", it.toJson()) }
        return json
    }
}

/**
 * Appearance shared by the annotation sub-lines beneath the main vocal line.
 */
data class LineNormalAnnotationBase(
    /**
     * Annotation font; the family inherits the normal-line base, while the explicit `%` size renders relative to that parent.
     *
     * @see line.normal.base.font
     */
    val font: CommonFontConfig? = null,
    /**
     * Annotation state styles; colors inherit the normal-line base, while explicit dimmer opacities let the rows recede beneath it.
     *
     * @see line.normal.base.style
     */
    val style: CommonStateStyleConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.font?.let { json.put("font", it.toJson()) }
        this.style?.let { json.put("style", it.toJson()) }
        return json
    }
}

/**
 * Romanization sub-line.
 */
data class LineNormalAnnotationRoman(
    /**
     * Whether the romanization row shows.
     *
     * @default true
     */
    val visible: Boolean? = null,
    /**
     * Preferred BCP-47 tag for the romanization; inherits the line base when left empty.
     *
     * @default ""
     * @see line.normal.base.language
     */
    val language: String? = null,
    /**
     * Row font; inherits the annotation base when unset.
     *
     * @see line.normal.annotation.base.font
     */
    val font: CommonFontConfig? = null,
    /**
     * Row styles; inherit the annotation base when unset.
     *
     * @see line.normal.annotation.base.style
     */
    val style: CommonStateStyleConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.visible?.let { json.put("visible", it) }
        this.language?.let { json.put("language", it) }
        this.font?.let { json.put("font", it.toJson()) }
        this.style?.let { json.put("style", it.toJson()) }
        return json
    }
}

/**
 * Translation sub-line.
 */
data class LineNormalAnnotationTranslate(
    /**
     * Whether the translation row shows.
     *
     * @default true
     */
    val visible: Boolean? = null,
    /**
     * Preferred BCP-47 tag for the translation; inherits the line base when left empty.
     *
     * @default ""
     * @see line.normal.base.language
     */
    val language: String? = null,
    /**
     * Row font; inherits the annotation base when unset.
     *
     * @see line.normal.annotation.base.font
     */
    val font: CommonFontConfig? = null,
    /**
     * Row styles; inherit the annotation base when unset.
     *
     * @see line.normal.annotation.base.style
     */
    val style: CommonStateStyleConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.visible?.let { json.put("visible", it) }
        this.language?.let { json.put("language", it) }
        this.font?.let { json.put("font", it.toJson()) }
        this.style?.let { json.put("style", it.toJson()) }
        return json
    }
}

/**
 * Geometry and state styles of instrumental-gap indicators.
 */
data class LineInterludeConfig(
    /**
     * Diameter of each indicator dot.
     * A bare number or `px` is an absolute length in logical pixels.
     *
     * @default "16px"
     * @example 16
     * @example "16px"
     */
    val size: String? = null,
    /**
     * Inactive and active dot styles.
     */
    val style: LineInterludeStateConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.size?.let { json.put("size", it) }
        this.style?.let { json.put("style", it.toJson()) }
        return json
    }
}

/**
 * Inactive and active styles of an interlude indicator.
 */
data class LineInterludeStateConfig(
    /**
     * Style before and after the interlude is active.
     */
    val normal: LineInterludeStyleConfig? = null,
    /**
     * Style progressively filled while the interlude is active.
     */
    val active: LineInterludeStyleConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.normal?.let { json.put("normal", it.toJson()) }
        this.active?.let { json.put("active", it.toJson()) }
        return json
    }
}

/**
 * Visual style for one playback state of an interlude indicator.
 */
data class LineInterludeStyleConfig(
    /**
     * Dot color for this playback state.
     * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
     *
     * @default "#ffffff"
     * @example "#fff"
     * @example "rgba(255, 255, 255, 0.8)"
     */
    val color: String? = null,
    /**
     * Dot opacity for this playback state.
     *
     * @default 1.0
     * @minimum 0
     * @maximum 1
     */
    val opacity: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.color?.let { json.put("color", it) }
        this.opacity?.let { json.put("opacity", it) }
        return json
    }
}

/**
 * Visual effects whose intensity depends on distance from the active line.
 *
 * Lines closer to the active one keep their natural look; lines farther away progressively shrink and/or blur.
 */
data class EffectConfig(
    /**
     * Scale (zoom) effect: shrinks lines farther from the active one.
     */
    val scale: EffectScaleConfig? = null,
    /**
     * Blur effect: blurs lines farther from the active one.
     */
    val blur: EffectBlurConfig? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.scale?.let { json.put("scale", it.toJson()) }
        this.blur?.let { json.put("blur", it.toJson()) }
        return json
    }
}

/**
 * Scale (zoom) effect applied per line.
 *
 * The active line uses `max`; the farthest lines collapse to `min`.
 */
data class EffectScaleConfig(
    /**
     * Whether to enable the scale effect.
     *
     * @default false
     */
    val enabled: Boolean? = null,
    /**
     * Scale ratio of the farthest line.
     *
     * @default 0.65
     */
    val min: Double? = null,
    /**
     * Scale ratio of the active line.
     *
     * @default 1.0
     */
    val max: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.min?.let { json.put("min", it) }
        this.max?.let { json.put("max", it) }
        return json
    }
}

/**
 * Blur effect applied per line.
 *
 * The active line uses `min` (sharpest); the farthest lines reach `max` (most blurred).
 */
data class EffectBlurConfig(
    /**
     * Whether to enable the blur effect.
     *
     * @default true
     */
    val enabled: Boolean? = null,
    /**
     * Blur radius of the active line in `px`, which is the sharpest state.
     *
     * @default 0.4
     */
    val min: Double? = null,
    /**
     * Blur radius of the farthest line in `px`, which is the most blurred state.
     *
     * @default 4.5
     */
    val max: Double? = null,
) {
    /**
     * Renders the fields that are set into a JSON object, leaving the rest out so the result stays a sparse patch.
     */
    fun toJson(): JSONObject {
        val json = JSONObject()
        this.enabled?.let { json.put("enabled", it) }
        this.min?.let { json.put("min", it) }
        this.max?.let { json.put("max", it) }
        return json
    }
}
