// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_CONFIG_GEN_H_

#include "rendering/config/line/interlude/index.gen.h"
#include "rendering/config/line/normal/index.gen.h"

namespace music_lyric_player::rendering::config::line {
	/**
	 * Normal-line rendering and instrumental-gap indicators.
	 */
	struct Root {
		/**
		 * Rendering settings of vocal lyric lines.
		 */
		::music_lyric_player::rendering::config::line::normal::Root normal;
		/**
		 * Instrumental-gap indicator geometry and animation styles.
		 */
		::music_lyric_player::rendering::config::line::interlude::Root interlude;
	};

	struct RootPatch {
		::music_lyric_player::rendering::config::line::normal::RootPatch normal;
		::music_lyric_player::rendering::config::line::interlude::RootPatch interlude;
	};

	struct RootChange {
		::music_lyric_player::rendering::config::line::normal::RootChange normal;
		::music_lyric_player::rendering::config::line::interlude::RootChange interlude;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.normal, patch.normal);
		apply(cfg.interlude, patch.interlude);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.normal = diff(prev.normal, next.normal);
		change.interlude = diff(prev.interlude, next.interlude);
		change.any = change.normal.any || change.interlude.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::line

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_CONFIG_GEN_H_
