// clang-format off

// Generated by generate-config script. DO NOT EDIT.
// To change config, edit the schema and regenerate with generate-config script.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_CONFIG_GEN_H_

#include "rendering/config/line/interlude/index.gen.h"
#include "rendering/config/line/normal/index.gen.h"

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::line {
	/**
	 * Normal-line rendering and instrumental-gap indicators.
	 */
	struct Root {
		/**
		 * Rendering settings of vocal lyric lines.
		 */
		::music_lyric_player::rendering::config::line::normal::Root normal;
		/**
		 * Instrumental-gap indicator geometry and animation styles.
		 */
		::music_lyric_player::rendering::config::line::interlude::Root interlude;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.normal, src.normal, key);
			overlay(dst.interlude, src.interlude, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.normal, prev.normal, next.normal, key);
			capture(delta.interlude, prev.interlude, next.interlude, key);
		}
	};

} // namespace music_lyric_player::rendering::config::line

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_CONFIG_GEN_H_
