// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_CONFIG_GEN_H_

#include "render/config/line/normal/main/index.gen.h"

namespace music_lyric_player::render::config::line::normal {
	/**
	 * Rendering settings of vocal lyric lines.
	 */
	struct Root {
		/**
		 * Rendering mode and settings of the main vocal content.
		 */
		::music_lyric_player::render::config::line::normal::main::Root main;
	};

	struct RootPatch {
		::music_lyric_player::render::config::line::normal::main::RootPatch main;
	};

	struct RootChange {
		::music_lyric_player::render::config::line::normal::main::RootChange main;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.main, patch.main);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.main = diff(prev.main, next.main);
		change.any = change.main.any;
		return change;
	}

} // namespace music_lyric_player::render::config::line::normal

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_CONFIG_GEN_H_
