#!/usr/bin/env python
"""
Embed an ICU common-data file (icudtl.dat) into a C++ translation unit.

The emitted source defines music_lyric_player_icu_data, a 16-byte aligned uint32 array that the SkLoadICU() override hands to ICU via udata_setCommonData.
No external icudtl.dat then has to ship next to the binary.

Usage: generate-icu-data.py <icudtl.dat> <output.cpp>
"""

import os
import struct
import sys


def generate(src_path, dst_path):
    """
    Read the ICU data blob at src_path and write its C++ array definition to dst_path.
    """
    with open(src_path, "rb") as src:
        blob = src.read()

    # ICU addresses the common data as little-endian 32-bit words; pad the tail so the length divides evenly.
    if len(blob) % 4:
        blob += b"\x00" * (4 - len(blob) % 4)
    words = struct.unpack("<%dI" % (len(blob) // 4), blob)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w", newline="\n") as dst:
        dst.write("// Generated by script/generate-icu-data.py; do not edit.\n")
        dst.write("#include <cstdint>\n\n")
        # The u suffix keeps every value an unsigned int so the braced initializer never narrows.
        dst.write("alignas(16) extern const std::uint32_t music_lyric_player_icu_data[] = {\n")
        for offset in range(0, len(words), 12):
            line = ",".join("%uu" % word for word in words[offset:offset + 12])
            dst.write("\t" + line + ",\n")
        dst.write("};\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: generate-icu-data.py <icudtl.dat> <output.cpp>")
    generate(sys.argv[1], sys.argv[2])
