// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONTAINER_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONTAINER_CONFIG_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_player::render::config::container {
	/**
	 * Background fill and padding of the player.
	 */
	struct Root {
		/**
		 * Background fill of the whole player.
		 * Accepts `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA`, `rgb(r, g, b)` or `rgba(r, g, b, a)` (a in 0..1).
		 *
		 * @default "#101014"
		 * @example "#101014"
		 * @example "rgb(16, 16, 20)"
		 */
		::std::string backgroundColor = "#101014";
		/**
		 * Horizontal padding on each side of the content.
		 * A `%` value is relative to the viewport width.
		 * A bare number or `px` is an absolute length in logical pixels.
		 *
		 * @default "48px"
		 * @example 48
		 * @example "48px"
		 * @example "5%"
		 */
		::std::string paddingX = "48px";
	};

	struct RootPatch {
		::std::optional<::std::string> backgroundColor;
		::std::optional<::std::string> paddingX;
	};

	struct RootChange {
		bool backgroundColor = false;
		bool paddingX = false;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		if (patch.backgroundColor.has_value()) {
			cfg.backgroundColor = *patch.backgroundColor;
		}
		if (patch.paddingX.has_value()) {
			cfg.paddingX = *patch.paddingX;
		}
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.backgroundColor = prev.backgroundColor != next.backgroundColor;
		change.paddingX = prev.paddingX != next.paddingX;
		change.any = change.backgroundColor || change.paddingX;
		return change;
	}

} // namespace music_lyric_player::render::config::container

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONTAINER_CONFIG_GEN_H_
