// clang-format off
// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONTAINER_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONTAINER_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"

namespace music_lyric_player::render::config::container {
	/**
	 * Background fill and padding of the player.
	 */
	struct Root {
		/**
		 * ARGB background fill of the whole player.
		 * @default 0xff101014u
		 */
		unsigned int backgroundColor = 0xff101014u;
		/**
		 * Horizontal padding on each side of the content.
		 * A bare number or `px` is absolute; `%` is relative to the viewport width.
		 *
		 * @default "48px"
		 * @example 48
		 * @example "48px"
		 * @example "5%"
		 */
		::std::string paddingX = "48px";
	};

	struct RootPatch {
		::std::optional<unsigned int> backgroundColor;
		::std::optional<::std::string> paddingX;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Root& cfg, const RootPatch& patch) {
		if (patch.backgroundColor.has_value()) {
			cfg.backgroundColor = *patch.backgroundColor;
		}
		if (patch.paddingX.has_value()) {
			cfg.paddingX = *patch.paddingX;
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Root& prev, const Root& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		if (prev.backgroundColor != next.backgroundColor) {
			keys.insert(prefix + "backgroundColor");
		}
		if (prev.paddingX != next.paddingX) {
			keys.insert(prefix + "paddingX");
		}
	}

	namespace RootKeys {
		inline constexpr ::std::string_view backgroundColor{"backgroundColor"};
		inline constexpr ::std::string_view paddingX{"paddingX"};
	} // namespace RootKeys

} // namespace music_lyric_player::render::config::container

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONTAINER_CONFIG_GEN_H_
// clang-format on
