// clang-format off
// Generated by script/generate-config.py from config.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"

namespace music_lyric_player::render {
	/**
	 * Basic renderer configuration (static layout; animation deferred).
	 */
	struct Config {
		::std::string fontFamily = {};  // system family name; empty uses the platform default
		double fontSize = 34.0;  // base font size in logical pixels
		double lineHeight = 1.3;  // line-height as a multiple of the font size
		double lineGap = 16.0;  // vertical gap between lines in logical pixels
		double paddingX = 48.0;  // horizontal padding on each side in logical pixels
		double anchor = 0.5;  // vertical anchor ratio (0 top .. 1 bottom) the focus line centers on
		int align = 0;  // text alignment: 0 left, 1 center, 2 right
		::std::string interludeText = "\u00b7 \u00b7 \u00b7";  // placeholder text drawn for interlude lines
		unsigned int backgroundColor = 0xff101014u;  // ARGB background fill
		unsigned int normalColor = 0x66ffffffu;  // ARGB color of inactive lines
		unsigned int activeColor = 0xffffffffu;  // ARGB color of the active line
		unsigned int interludeColor = 0x4dffffffu;  // ARGB color of interlude markers
	};

	struct ConfigPatch {
		::std::optional<::std::string> fontFamily;
		::std::optional<double> fontSize;
		::std::optional<double> lineHeight;
		::std::optional<double> lineGap;
		::std::optional<double> paddingX;
		::std::optional<double> anchor;
		::std::optional<int> align;
		::std::optional<::std::string> interludeText;
		::std::optional<unsigned int> backgroundColor;
		::std::optional<unsigned int> normalColor;
		::std::optional<unsigned int> activeColor;
		::std::optional<unsigned int> interludeColor;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Config& cfg, const ConfigPatch& patch) {
		if (patch.fontFamily.has_value()) {
			cfg.fontFamily = *patch.fontFamily;
		}
		if (patch.fontSize.has_value()) {
			cfg.fontSize = *patch.fontSize;
		}
		if (patch.lineHeight.has_value()) {
			cfg.lineHeight = *patch.lineHeight;
		}
		if (patch.lineGap.has_value()) {
			cfg.lineGap = *patch.lineGap;
		}
		if (patch.paddingX.has_value()) {
			cfg.paddingX = *patch.paddingX;
		}
		if (patch.anchor.has_value()) {
			cfg.anchor = *patch.anchor;
		}
		if (patch.align.has_value()) {
			cfg.align = *patch.align;
		}
		if (patch.interludeText.has_value()) {
			cfg.interludeText = *patch.interludeText;
		}
		if (patch.backgroundColor.has_value()) {
			cfg.backgroundColor = *patch.backgroundColor;
		}
		if (patch.normalColor.has_value()) {
			cfg.normalColor = *patch.normalColor;
		}
		if (patch.activeColor.has_value()) {
			cfg.activeColor = *patch.activeColor;
		}
		if (patch.interludeColor.has_value()) {
			cfg.interludeColor = *patch.interludeColor;
		}
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Config& prev, const Config& next, const ::std::string& prefix, ::music_lyric_player::ChangeKeys& keys) {
		if (prev.fontFamily != next.fontFamily) {
			keys.insert(prefix + "fontFamily");
		}
		if (prev.fontSize != next.fontSize) {
			keys.insert(prefix + "fontSize");
		}
		if (prev.lineHeight != next.lineHeight) {
			keys.insert(prefix + "lineHeight");
		}
		if (prev.lineGap != next.lineGap) {
			keys.insert(prefix + "lineGap");
		}
		if (prev.paddingX != next.paddingX) {
			keys.insert(prefix + "paddingX");
		}
		if (prev.anchor != next.anchor) {
			keys.insert(prefix + "anchor");
		}
		if (prev.align != next.align) {
			keys.insert(prefix + "align");
		}
		if (prev.interludeText != next.interludeText) {
			keys.insert(prefix + "interludeText");
		}
		if (prev.backgroundColor != next.backgroundColor) {
			keys.insert(prefix + "backgroundColor");
		}
		if (prev.normalColor != next.normalColor) {
			keys.insert(prefix + "normalColor");
		}
		if (prev.activeColor != next.activeColor) {
			keys.insert(prefix + "activeColor");
		}
		if (prev.interludeColor != next.interludeColor) {
			keys.insert(prefix + "interludeColor");
		}
	}

	namespace ConfigKeys {
		inline constexpr ::std::string_view fontFamily{"fontFamily"};
		inline constexpr ::std::string_view fontSize{"fontSize"};
		inline constexpr ::std::string_view lineHeight{"lineHeight"};
		inline constexpr ::std::string_view lineGap{"lineGap"};
		inline constexpr ::std::string_view paddingX{"paddingX"};
		inline constexpr ::std::string_view anchor{"anchor"};
		inline constexpr ::std::string_view align{"align"};
		inline constexpr ::std::string_view interludeText{"interludeText"};
		inline constexpr ::std::string_view backgroundColor{"backgroundColor"};
		inline constexpr ::std::string_view normalColor{"normalColor"};
		inline constexpr ::std::string_view activeColor{"activeColor"};
		inline constexpr ::std::string_view interludeColor{"interludeColor"};
	} // namespace ConfigKeys

} // namespace music_lyric_player::render

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_GEN_H_
// clang-format on
