// clang-format off

// Generated by script/generate-config.py from config.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONFIG_GEN_H_

#include "render/config/container/index.gen.h"
#include "render/config/layout/index.gen.h"
#include "render/config/line/index.gen.h"
#include "render/config/scroll/index.gen.h"

namespace music_lyric_player::render::config {
	/**
	 * Renderer configuration.
	 */
	struct Root {
		/**
		 * Background fill and padding of the player.
		 */
		::music_lyric_player::render::config::container::Root container;
		/**
		 * Alignment and spacing between lyric lines.
		 */
		::music_lyric_player::render::config::layout::Root layout;
		/**
		 * Viewport scrolling and its transition animation.
		 */
		::music_lyric_player::render::config::scroll::Root scroll;
		/**
		 * Font and per-state colors of lyric lines.
		 */
		::music_lyric_player::render::config::line::Root line;
	};

	struct RootPatch {
		::music_lyric_player::render::config::container::RootPatch container;
		::music_lyric_player::render::config::layout::RootPatch layout;
		::music_lyric_player::render::config::scroll::RootPatch scroll;
		::music_lyric_player::render::config::line::RootPatch line;
	};

	struct RootChange {
		::music_lyric_player::render::config::container::RootChange container;
		::music_lyric_player::render::config::layout::RootChange layout;
		::music_lyric_player::render::config::scroll::RootChange scroll;
		::music_lyric_player::render::config::line::RootChange line;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.container, patch.container);
		apply(cfg.layout, patch.layout);
		apply(cfg.scroll, patch.scroll);
		apply(cfg.line, patch.line);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.container = diff(prev.container, next.container);
		change.layout = diff(prev.layout, next.layout);
		change.scroll = diff(prev.scroll, next.scroll);
		change.line = diff(prev.line, next.line);
		change.any = change.container.any || change.layout.any || change.scroll.any || change.line.any;
		return change;
	}

	/**
	 * Built-in defaults (every field at its schema default); the fallback when a config value fails to parse.
	 */
	inline const Root Default{};

} // namespace music_lyric_player::render::config

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONFIG_GEN_H_
