// clang-format off
// Generated by script/generate-config.py from config.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.
#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONFIG_GEN_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>

#include "utils/manager/config.h"
#include "render/config/container/index.gen.h"
#include "render/config/layout/index.gen.h"
#include "render/config/line/index.gen.h"
#include "render/config/scroll/index.gen.h"

namespace music_lyric_player::render::config {
	/**
	 * Renderer configuration, split by concern like the web player.
	 * Each domain lives in its own sub-module.
	 */
	struct Root {
		/**
		 * Outer wrapper: background fill and padding.
		 */
		::music_lyric_player::render::config::container::Root container;
		/**
		 * Geometric layout: alignment and inter-line spacing.
		 */
		::music_lyric_player::render::config::layout::Root layout;
		/**
		 * Viewport scrolling and transition animation.
		 */
		::music_lyric_player::render::config::scroll::Root scroll;
		/**
		 * Lyric line rendering: shared font and per-state colors.
		 */
		::music_lyric_player::render::config::line::Root line;
	};

	struct RootPatch {
		::music_lyric_player::render::config::container::RootPatch container;
		::music_lyric_player::render::config::layout::RootPatch layout;
		::music_lyric_player::render::config::scroll::RootPatch scroll;
		::music_lyric_player::render::config::line::RootPatch line;
	};

	/**
	 * Deep-merges a sparse patch into a config.
	 */
	inline void applyConfigPatch(Root& cfg, const RootPatch& patch) {
		applyConfigPatch(cfg.container, patch.container);
		applyConfigPatch(cfg.layout, patch.layout);
		applyConfigPatch(cfg.scroll, patch.scroll);
		applyConfigPatch(cfg.line, patch.line);
	}

	/**
	 * Diffs two configs into a dot-path key set; a changed child also records its parent path.
	 */
	inline void diffConfig(const Root& prev, const Root& next, const ::std::string& prefix, ::music_lyric_player::utils::config::ChangeKeys& keys) {
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.container, next.container, prefix + "container" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "container");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.layout, next.layout, prefix + "layout" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "layout");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.scroll, next.scroll, prefix + "scroll" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "scroll");
			}
		}
		{
			const ::std::size_t before = keys.size();
			diffConfig(prev.line, next.line, prefix + "line" + ".", keys);
			if (keys.size() > before) {
				keys.insert(prefix + "line");
			}
		}
	}

	namespace RootKeys {
		namespace container {
			inline constexpr ::std::string_view backgroundColor{"container.backgroundColor"};
			inline constexpr ::std::string_view paddingX{"container.paddingX"};
		} // namespace container
		namespace layout {
			inline constexpr ::std::string_view align{"layout.align"};
			inline constexpr ::std::string_view gap{"layout.gap"};
		} // namespace layout
		namespace scroll {
			inline constexpr ::std::string_view anchor{"scroll.anchor"};
			namespace animation {
				inline constexpr ::std::string_view duration{"scroll.animation.duration"};
			} // namespace animation
		} // namespace scroll
		namespace line {
			namespace font {
				inline constexpr ::std::string_view family{"line.font.family"};
				inline constexpr ::std::string_view size{"line.font.size"};
			} // namespace font
			namespace normal {
				inline constexpr ::std::string_view color{"line.normal.color"};
			} // namespace normal
			namespace active {
				inline constexpr ::std::string_view color{"line.active.color"};
			} // namespace active
		} // namespace line
	} // namespace RootKeys

} // namespace music_lyric_player::render::config

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_CONFIG_GEN_H_
// clang-format on
