"""Glaze enum-name meta header generation (enums serialize by name, not integer, on the JSON wire)."""

from pathlib import Path

from model import include_path_for
from emit import collect_enums


def collect_all_enums(module, seen=None, out=None):
    """Every (namespace, enum_name, values) across a module and its transitive imports, de-duplicated by path."""
    seen = seen if seen is not None else set()
    out = out if out is not None else []
    key = module.path.resolve()
    if key in seen:
        return out
    seen.add(key)
    for name, (values, _comment) in collect_enums(module).items():
        out.append((module.namespace, name, values))
    for imported in module.imports.values():
        collect_all_enums(imported, seen, out)
    return out


def glaze_file_name(header_file):
    """The Glaze meta header paired with a generated header (`x.gen.h` -> `x.gen.glaze.h`)."""
    if header_file.endswith(".gen.h"):
        return header_file[: -len(".gen.h")] + ".gen.glaze.h"
    return Path(header_file).stem + ".gen.glaze.h"


def render_glaze(module, schema_name):
    """Render the Glaze enum-name meta header for a root config, or None when its tree declares no enums.

    Glaze serializes enums as integers pre-C++26, so a `glz::meta` per enum names its enumerators on the wire.
    """
    enums = collect_all_enums(module)
    if not enums:
        return None
    guard = module.namespace.replace("::", "_").upper() + "_CONFIG_GLAZE_H_"
    parts = [
        f"// Generated by script/generate-config/main.py from {schema_name}. DO NOT EDIT.",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "glaze/json.hpp"',
        f'#include "{include_path_for(module.path.parent / module.file)}"',
    ]
    for namespace, name, values in enums:
        full = f"::{namespace}::{name}"
        parts += [
            "",
            "template <>",
            f"struct glz::meta<{full}> {{",
            f"\tusing enum {full};",
            f"\tstatic constexpr auto value = enumerate({', '.join(values)});",
            "};",
        ]
    parts += ["", f"#endif // {guard}"]
    return "\n".join(parts) + "\n"
