// clang-format off

// Generated by generate-config script. DO NOT EDIT.
// To change config, edit the schema and regenerate with generate-config script.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_CONFIG_GEN_H_

#include "rendering/config/common/index.gen.h"
#include "rendering/config/line/normal/main/index.gen.h"

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::line::normal {
	/**
	 * Appearance shared by the main vocal line and its annotation sub-lines.
	 */
	struct Base {
		/**
		 * Font shared by every line.
		 */
		::music_lyric_player::rendering::config::common::FontConfig font;
		/**
		 * Inactive and active styles shared by normal lyric lines.
		 */
		::music_lyric_player::rendering::config::common::StateStyleConfig style;

		bool operator==(const Base&) const = default;

		friend void overlay(Base& dst, const Base& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.font, src.font, key);
			overlay(dst.style, src.style, key);
		}

		friend void capture(Base& delta, const Base& prev, const Base& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.font, prev.font, next.font, key);
			capture(delta.style, prev.style, next.style, key);
		}
	};

	/**
	 * Rendering settings of vocal lyric lines.
	 */
	struct Root {
		/**
		 * Appearance shared by the main vocal line and its annotation sub-lines.
		 */
		Base base;
		/**
		 * Rendering mode and settings of the main vocal content.
		 */
		::music_lyric_player::rendering::config::line::normal::main::Root main;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.base, src.base, key);
			overlay(dst.main, src.main, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.base, prev.base, next.base, key);
			capture(delta.main, prev.main, next.main, key);
		}
	};

} // namespace music_lyric_player::rendering::config::line::normal

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_CONFIG_GEN_H_
