// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_CONFIG_GEN_H_

#include "rendering/config/common/index.gen.h"
#include "rendering/config/line/normal/main/index.gen.h"

namespace music_lyric_player::rendering::config::line::normal {
	/**
	 * Appearance shared by the main vocal line and its annotation sub-lines.
	 */
	struct Base {
		/**
		 * Font shared by every line.
		 */
		::music_lyric_player::rendering::config::common::FontConfig font;
		/**
		 * Inactive and active styles shared by normal lyric lines.
		 */
		::music_lyric_player::rendering::config::common::StateStyleConfig style;
	};

	/**
	 * Rendering settings of vocal lyric lines.
	 */
	struct Root {
		/**
		 * Appearance shared by the main vocal line and its annotation sub-lines.
		 */
		Base base;
		/**
		 * Rendering mode and settings of the main vocal content.
		 */
		::music_lyric_player::rendering::config::line::normal::main::Root main;
	};

	struct BasePatch {
		::music_lyric_player::rendering::config::common::FontConfigPatch font;
		::music_lyric_player::rendering::config::common::StateStyleConfigPatch style;
	};

	struct RootPatch {
		BasePatch base;
		::music_lyric_player::rendering::config::line::normal::main::RootPatch main;
	};

	struct BaseChange {
		::music_lyric_player::rendering::config::common::FontConfigChange font;
		::music_lyric_player::rendering::config::common::StateStyleConfigChange style;
		bool any = false;
	};

	struct RootChange {
		BaseChange base;
		::music_lyric_player::rendering::config::line::normal::main::RootChange main;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Base& cfg, const BasePatch& patch) {
		apply(cfg.font, patch.font);
		apply(cfg.style, patch.style);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.base, patch.base);
		apply(cfg.main, patch.main);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline BaseChange diff(const Base& prev, const Base& next) {
		BaseChange change;
		change.font = diff(prev.font, next.font);
		change.style = diff(prev.style, next.style);
		change.any = change.font.any || change.style.any;
		return change;
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.base = diff(prev.base, next.base);
		change.main = diff(prev.main, next.main);
		change.any = change.base.any || change.main.any;
		return change;
	}

} // namespace music_lyric_player::rendering::config::line::normal

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_CONFIG_GEN_H_
