// clang-format off

// Generated by generate-config script. DO NOT EDIT.
// To change config, edit the schema and regenerate with generate-config script.

#ifndef MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_ANNOTATION_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_ANNOTATION_CONFIG_GEN_H_

#include "rendering/config/common/index.gen.h"

#include "utils/config/access.h"
#include "utils/config/property.h"

namespace music_lyric_player::rendering::config::line::normal::annotation {
	/**
	 * Appearance shared by the annotation sub-lines beneath the main vocal line.
	 */
	struct Base {
		/**
		 * Annotation font; the family inherits the normal-line base, while the explicit `%` size renders relative to that parent.
		 */
		::music_lyric_player::rendering::config::common::FontConfig font = ::music_lyric_player::rendering::config::common::FontConfig{ .size = "60%" };
		/**
		 * Annotation state styles; colors inherit the normal-line base, while explicit dimmer opacities let the rows recede beneath it.
		 */
		::music_lyric_player::rendering::config::common::StateStyleConfig style = ::music_lyric_player::rendering::config::common::StateStyleConfig{ .normal = ::music_lyric_player::rendering::config::common::StyleConfig{ .opacity = 0.4 }, .active = ::music_lyric_player::rendering::config::common::StyleConfig{ .opacity = 0.6 }, .played = ::music_lyric_player::rendering::config::common::StyleConfig{ .opacity = 0.4 } };

		bool operator==(const Base&) const = default;

		friend void overlay(Base& dst, const Base& src, ::music_lyric_player::utils::config::Access key) {
			overlay(dst.font, src.font, key);
			overlay(dst.style, src.style, key);
		}

		friend void capture(Base& delta, const Base& prev, const Base& next, ::music_lyric_player::utils::config::Access key) {
			capture(delta.font, prev.font, next.font, key);
			capture(delta.style, prev.style, next.style, key);
		}
	};

	/**
	 * Romanization sub-line.
	 */
	struct Roman {
		/**
		 * Whether the romanization row shows.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> visible = true;
		/**
		 * Row font; inherits the annotation base when unset.
		 */
		::music_lyric_player::rendering::config::common::FontConfig font;
		/**
		 * Row styles; inherit the annotation base when unset.
		 */
		::music_lyric_player::rendering::config::common::StateStyleConfig style;

		bool operator==(const Roman&) const = default;

		friend void overlay(Roman& dst, const Roman& src, ::music_lyric_player::utils::config::Access key) {
			if (src.visible.assigned()) dst.visible = src.visible.value();
			overlay(dst.font, src.font, key);
			overlay(dst.style, src.style, key);
		}

		friend void capture(Roman& delta, const Roman& prev, const Roman& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.visible == next.visible)) delta.visible = next.visible.value();
			capture(delta.font, prev.font, next.font, key);
			capture(delta.style, prev.style, next.style, key);
		}
	};

	/**
	 * Translation sub-line.
	 */
	struct Translate {
		/**
		 * Whether the translation row shows.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> visible = true;
		/**
		 * Row font; inherits the annotation base when unset.
		 */
		::music_lyric_player::rendering::config::common::FontConfig font;
		/**
		 * Row styles; inherit the annotation base when unset.
		 */
		::music_lyric_player::rendering::config::common::StateStyleConfig style;

		bool operator==(const Translate&) const = default;

		friend void overlay(Translate& dst, const Translate& src, ::music_lyric_player::utils::config::Access key) {
			if (src.visible.assigned()) dst.visible = src.visible.value();
			overlay(dst.font, src.font, key);
			overlay(dst.style, src.style, key);
		}

		friend void capture(Translate& delta, const Translate& prev, const Translate& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.visible == next.visible)) delta.visible = next.visible.value();
			capture(delta.font, prev.font, next.font, key);
			capture(delta.style, prev.style, next.style, key);
		}
	};

	/**
	 * Annotation sub-lines beneath the main vocal line.
	 */
	struct Root {
		/**
		 * Master switch; when false both rows hide regardless of their own visible.
		 *
		 * @default true
		 */
		::music_lyric_player::utils::config::Property<bool> visible = true;
		/**
		 * Shared base inherited by all annotation rows.
		 */
		Base base;
		/**
		 * Romanization row overrides.
		 */
		Roman roman;
		/**
		 * Translation row overrides.
		 */
		Translate translate;

		bool operator==(const Root&) const = default;

		friend void overlay(Root& dst, const Root& src, ::music_lyric_player::utils::config::Access key) {
			if (src.visible.assigned()) dst.visible = src.visible.value();
			overlay(dst.base, src.base, key);
			overlay(dst.roman, src.roman, key);
			overlay(dst.translate, src.translate, key);
		}

		friend void capture(Root& delta, const Root& prev, const Root& next, ::music_lyric_player::utils::config::Access key) {
			if (!(prev.visible == next.visible)) delta.visible = next.visible.value();
			capture(delta.base, prev.base, next.base, key);
			capture(delta.roman, prev.roman, next.roman, key);
			capture(delta.translate, prev.translate, next.translate, key);
		}
	};

} // namespace music_lyric_player::rendering::config::line::normal::annotation

#endif // MUSIC_LYRIC_PLAYER_RENDERING_CONFIG_LINE_NORMAL_ANNOTATION_CONFIG_GEN_H_
