// clang-format off

// Generated by script/generate-config.py from index.schema.json. DO NOT EDIT.
// To change config, edit the schema and regenerate with script/generate-config.py.

#ifndef MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_CONFIG_GEN_H_
#define MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_CONFIG_GEN_H_

#include "render/config/line/normal/main/syllable/word/index.gen.h"

namespace music_lyric_player::render::config::line::normal::main::syllable {
	/**
	 * Word-timed karaoke rendering settings.
	 */
	struct Root {
		/**
		 * Timed word rendering and animation settings.
		 */
		::music_lyric_player::render::config::line::normal::main::syllable::word::Root word;
	};

	struct RootPatch {
		::music_lyric_player::render::config::line::normal::main::syllable::word::RootPatch word;
	};

	struct RootChange {
		::music_lyric_player::render::config::line::normal::main::syllable::word::RootChange word;
		bool any = false;
	};

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline void apply(Root& cfg, const RootPatch& patch) {
		apply(cfg.word, patch.word);
	}

	/**
	 * Called by the config Manager and the parent aggregate, not part of the public API.
	 */
	inline RootChange diff(const Root& prev, const Root& next) {
		RootChange change;
		change.word = diff(prev.word, next.word);
		change.any = change.word.any;
		return change;
	}

} // namespace music_lyric_player::render::config::line::normal::main::syllable

#endif // MUSIC_LYRIC_PLAYER_RENDER_CONFIG_LINE_NORMAL_MAIN_SYLLABLE_CONFIG_GEN_H_
